const crypto=require('crypto');
const P=String.fromCharCode(36);
function ipKey(data){return String(data.ip||'unknown');}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim())&&String(v).length<=200;}
function passwordBytes(v){return Buffer.byteLength(String(v||''),'utf8');}
function validPassword(v){const value=String(v||'');return value.length>=12&&value.length<=128&&passwordBytes(value)<=256;}
function rate(map,key,limit,windowMs){const now=Date.now();if(map.size>10000){for(const [k,v] of map){if(now-v.start>windowMs)map.delete(k)}if(map.size>12000){let drop=map.size-10000;for(const k of map.keys()){map.delete(k);if(--drop<=0)break}}}const row=map.get(key);if(!row||now-row.start>windowMs){map.set(key,{start:now,count:1});return true}row.count++;return row.count<=limit;}
const loginRate=new Map();
const loginAccountRate=new Map();
const resetRate=new Map();
function sessionToken(){return crypto.randomBytes(32).toString('base64url');}
function sessionHash(v){return crypto.createHash('sha256').update(String(v)).digest('hex');}
const SCRYPT_N=131072,SCRYPT_R=8,SCRYPT_P=1,SCRYPT_MAXMEM=192*1024*1024;
function hashPassword(password){return new Promise((resolve,reject)=>{const salt=crypto.randomBytes(16);crypto.scrypt(String(password),salt,64,{N:SCRYPT_N,r:SCRYPT_R,p:SCRYPT_P,maxmem:SCRYPT_MAXMEM},(err,key)=>err?reject(err):resolve(['scrypt',String(SCRYPT_N),String(SCRYPT_R),String(SCRYPT_P),salt.toString('hex'),key.toString('hex')].join(P)));});}
function verifyPassword(password,stored){return new Promise(resolve=>{try{const a=String(stored||'').split(P);if(a[0]!=='scrypt')return resolve(false);const salt=Buffer.from(a[4],'hex'),expected=Buffer.from(a[5],'hex'),N=Number(a[1]),r=Number(a[2]),p=Number(a[3]);crypto.scrypt(String(password),salt,expected.length,{N,r,p,maxmem:Math.max(SCRYPT_MAXMEM,128*N*r+8*1024*1024)},(err,key)=>resolve(!err&&key.length===expected.length&&crypto.timingSafeEqual(key,expected)));}catch(_){resolve(false);}});}
function passwordNeedsRehash(stored){try{const a=String(stored||'').split(P);return a[0]!=='scrypt'||Number(a[1])<SCRYPT_N||Number(a[2])!==SCRYPT_R||Number(a[3])!==SCRYPT_P}catch(_){return true}}
async function createAccount(deps,data){const {db,normalizeName,validName,validCountry,publicPlayer}=deps;const email=String(data.email||'').trim().toLowerCase(),name=String(data.name||'').trim(),country=String(data.country||'').trim().toUpperCase(),password=String(data.password||'');if(!validEmail(email))throw Object.assign(new Error('Email inválido.'),{status:400});if(!validPassword(password))throw Object.assign(new Error('A palavra-passe deve ter pelo menos 12 caracteres.'),{status:400});if(!validName(name))throw Object.assign(new Error('Nome inválido. Usa 3–8 letras ou números, sem espaços ou símbolos.'),{status:400});if(!validCountry(country))throw Object.assign(new Error('País inválido.'),{status:400});const accountId=crypto.randomUUID(),playerId=crypto.randomUUID(),hash=await hashPassword(password),session=sessionToken(),client=await db.connect();try{await client.query('BEGIN');const e=await client.query('SELECT 1 FROM accounts WHERE email='+P+'1',[email]);if(e.rowCount)throw Object.assign(new Error('Já existe uma conta com esse email.'),{status:409});const n=await client.query('SELECT 1 FROM players WHERE name_key='+P+'1',[normalizeName(name)]);if(n.rowCount)throw Object.assign(new Error('Esse nome já está a ser utilizado.'),{status:409});await client.query('INSERT INTO accounts(id,email,password_hash) VALUES('+P+'1,'+P+'2,'+P+'3)',[accountId,email,hash]);await client.query('INSERT INTO players(id,name,name_key,country,account_id,visual_name) VALUES('+P+'1,'+P+'2,'+P+'3,'+P+'4,'+P+'5,'+P+'2)',[playerId,name,normalizeName(name),country,accountId]);await client.query('INSERT INTO sessions(id,account_id,token_hash,expires_at) VALUES('+P+'1,'+P+'2,'+P+'3,NOW()+INTERVAL \'30 days\')',[crypto.randomUUID(),accountId,sessionHash(session)]);await client.query('COMMIT');const p=await deps.authenticate(playerId,session);return{player:publicPlayer(p),session};}catch(e){try{await client.query('ROLLBACK')}catch(_){}throw e;}finally{client.release();}}
async function loginAccount(deps,data){const {db,authenticate,publicPlayer}=deps;const email=String(data.email||'').trim().toLowerCase(),password=String(data.password||'');if(!validEmail(email)||String(password).length>128||passwordBytes(password)>256)throw Object.assign(new Error('Credenciais inválidas.'),{status:401});if(!rate(loginRate,'login:'+ipKey(data),10,900000)||!rate(loginAccountRate,'account:'+email,8,900000))throw Object.assign(new Error('Demasiadas tentativas. Tenta novamente mais tarde.'),{status:429});const r=await db.query('SELECT a.id,a.password_hash,p.id AS player_id FROM accounts a JOIN players p ON p.account_id=a.id WHERE a.email='+P+'1',[email]);const row=r.rows[0];if(!row||!(await verifyPassword(password,row.password_hash)))throw Object.assign(new Error('Credenciais inválidas.'),{status:401});if(passwordNeedsRehash(row.password_hash)){try{const upgraded=await hashPassword(password);await db.query('UPDATE accounts SET password_hash='+P+'1,updated_at=NOW() WHERE id='+P+'2',[upgraded,row.id]);}catch(e){console.warn('Password rehash deferred for account',row.id,e?.code||e?.message||e);}}const session=sessionToken();await db.query('INSERT INTO sessions(id,account_id,token_hash,expires_at) VALUES('+P+'1,'+P+'2,'+P+'3,NOW()+INTERVAL \'30 days\')',[crypto.randomUUID(),row.id,sessionHash(session)]);const p=await authenticate(row.player_id,session);return{player:publicPlayer(p),session};}
async function logout(db,token){if(token)await db.query('DELETE FROM sessions WHERE token_hash='+P+'1',[sessionHash(token)]);return{ok:true};}
async function requestReset(db,data){if(!rate(resetRate,'reset:'+ipKey(data),5,900000))throw Object.assign(new Error('Demasiados pedidos. Tenta novamente mais tarde.'),{status:429});const email=String(data.email||'').trim().toLowerCase();if(!validEmail(email))throw Object.assign(new Error('Email inválido.'),{status:400});const r=await db.query('SELECT id FROM accounts WHERE email='+P+'1',[email]);if(r.rowCount){const token=crypto.randomBytes(32).toString('base64url');await db.query('DELETE FROM password_reset_tokens WHERE account_id='+P+'1',[r.rows[0].id]);await db.query('INSERT INTO password_reset_tokens(id,account_id,token_hash,expires_at) VALUES('+P+'1,'+P+'2,'+P+'3,NOW()+INTERVAL \'30 minutes\')',[crypto.randomUUID(),r.rows[0].id,sessionHash(token)]);}return{ok:true,message:'Se o email existir, receberás instruções para recuperar a palavra-passe.'};}
async function resetPassword(db,data){const token=String(data.token||''),password=String(data.password||'');if(!token||!validPassword(password))throw Object.assign(new Error('Token ou palavra-passe inválidos.'),{status:400});const r=await db.query('SELECT id,account_id FROM password_reset_tokens WHERE token_hash='+P+'1 AND expires_at>NOW() AND used_at IS NULL',[sessionHash(token)]);if(!r.rowCount)throw Object.assign(new Error('Token inválido ou expirado.'),{status:400});const hash=await hashPassword(password),client=await db.connect();try{await client.query('BEGIN');await client.query('UPDATE accounts SET password_hash='+P+'1,updated_at=NOW() WHERE id='+P+'2',[hash,r.rows[0].account_id]);await client.query('UPDATE password_reset_tokens SET used_at=NOW() WHERE id='+P+'1',[r.rows[0].id]);await client.query('DELETE FROM sessions WHERE account_id='+P+'1',[r.rows[0].account_id]);await client.query('COMMIT');return{ok:true};}catch(e){try{await client.query('ROLLBACK')}catch(_){}throw e;}finally{client.release();}}
module.exports={createAccount,loginAccount,logout,requestReset,resetPassword,verifyPassword};