/* EIXO UX layer: persistent session validation, room entry, contact/bug forms and rank-based name customization. */
(function(){
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
 const player=()=>{try{return JSON.parse(localStorage.getItem('eixo_player')||'null')}catch(_){return null}};
 const open=id=>$(id)?.classList.remove('hidden'),close=id=>$(id)?.classList.add('hidden');
 const getAuth=()=>{const p=player();return p?{id:p.id,token:p.token}:null};
 const ALL=['#ffffff','#ff4d4d','#ff7a2f','#ffd43b','#7bdc5a','#39d98a','#00d4ff','#3b82f6','#6f5cff','#b66cff','#ff4fd8','#ff6b9d','#a8e063','#00f0ff','#f97316','#facc15','#94a3b8','#e2e8f0','#22c55e','#ef4444','rainbow'];
 const WORLD=['#39d98a','#3b82f6','#f59e0b'],COUNTRY=['#ffd43b','#b66cff','#ff7a2f'],COUNTRY_OTHER=['#00d4ff','#ff4fd8','#ffffff'];
 const EFFECTS=[['none','Nenhum'],['bounce','Salta'],['glow','Brilha'],['wave','Onda'],['shake','Treme'],['float','Flutua'],['pulse','Pulsa'],['jelly','Gelatina']];
 const effectClass=e=>`effect-${e||'none'}`;
 async function validateSession(){const p=player();if(!p?.id||!p?.token)return;try{const r=await fetch(`/api/me?id=${encodeURIComponent(p.id)}&token=${encodeURIComponent(p.token)}`,{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();localStorage.setItem('eixo_player',JSON.stringify({...p,...d.player,token:p.token}));window.dispatchEvent(new Event('eixo-player-updated'));}catch(_){localStorage.removeItem('eixo_player');localStorage.removeItem('eixo_country');location.reload();}}
 validateSession();
 window.addEventListener('eixo-player-menu',e=>{if(e.detail.action==='contact')open('contactModal');if(e.detail.action==='bugs')open('bugModal');if(e.detail.action==='customize')openCustomize();});
 document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>close(b.dataset.closeModal)));
 document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));
 async function sendForm(form,type,errorId){const err=$(errorId);err.textContent='';const data=Object.fromEntries(new FormData(form).entries());try{const r=await fetch('/api/'+type,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível enviar.');form.reset();close(form.closest('.modal-backdrop').id);alert(window.eixoT?window.eixoT('messageSent','Message sent. Thank you!'):'Message sent. Thank you!');}catch(e){err.textContent=e.message;}}
 $('contactForm')?.addEventListener('submit',e=>{e.preventDefault();sendForm(e.currentTarget,'contact','contactError')});
 $('bugForm')?.addEventListener('submit',e=>{e.preventDefault();sendForm(e.currentTarget,'bugs','bugError')});
 async function topData(){const p=player();if(!p?.id||!p?.token)return null;const r=await fetch(`/api/player-rank?id=${encodeURIComponent(p.id)}&token=${encodeURIComponent(p.token)}`,{cache:'no-store'});if(!r.ok)throw Error('Ranking indisponível');const d=await r.json();return{p,worldRank:Number(d.worldRank)||9999,countryRank:Number(d.countryRank)||9999};}
 window.eixoOpenCustomize=()=>openCustomize();
 async function openCustomize(){const p=player();if(!p)return;if(Number(p.vipLevel||0)>0&&window.eixoOpenVipCustomize){window.eixoOpenVipCustomize();return;}const modal=$('customizeModal'),name=$('customizeName'),color=$('customizeColor'),effect=$('customizeEffect'),hint=$('customizeHint'),wrap=$('customizeNameWrap'),err=$('customizeError');err.textContent='';try{const r=await topData();if(!r)return;const isW1=r.worldRank===1,isW23=r.worldRank===2||r.worldRank===3,isC1=r.countryRank===1,isC23=r.countryRank===2||r.countryRank===3;const eligible=isW1||isW23||isC1||isC23;const canEffect=isW1||r.worldRank===2||r.countryRank===1||r.countryRank===2;if(!eligible){hint.textContent='A personalização está disponível apenas para TOP 1/2/3 mundial ou TOP 1/2/3 do país.';return}let colors=[];if(isW1)colors=ALL;else if(isW23)colors=WORLD;else if(isC1)colors=COUNTRY;else if(isC23)colors=COUNTRY_OTHER;else{hint.textContent='Não tens opções especiais disponíveis neste momento.';return}color.innerHTML=colors.map(c=>`<option value="${c}">${c==='rainbow'?'🌈 ARCO-ÍRIS':c}</option>`).join('');color.value=colors.includes(p.nameColor)?p.nameColor:colors[0];effect.innerHTML=EFFECTS.map(([v,l])=>`<option value="${v}">${l}</option>`).join('');effect.value=canEffect?(p.nameEffect||'none'):'none';wrap.style.display=isW1?'block':'none';name.value=p.visualName||p.name;hint.textContent=isW1?'TOP 1 MUNDIAL: podes mudar o nome visual, cor e efeito. O nome oficial da conta não muda.':isW23?'TOP 2/3 MUNDIAL: podes escolher uma das 3 cores especiais. O TOP 2 também pode usar efeitos.':isC1?'TOP 1 DO PAÍS: podes escolher uma das 3 cores nacionais e usar efeitos.':isC23?'TOP 2/3 DO PAÍS: podes escolher uma das 3 cores reservadas. O TOP 2 também pode usar efeitos.':'Não tens opções especiais disponíveis neste momento.';updatePreview();open('customizeModal');}catch(e){err.textContent=e.message}}
 function updatePreview(){const n=$('customizeName'),c=$('customizeColor'),e=$('customizeEffect'),p=$('namePreview');if(!p)return;p.textContent=n?.value||player()?.visualName||player()?.name||'JOGADOR';p.className='name-preview '+effectClass(e?.value)+(c?.value==='rainbow'?' name-rainbow':'');p.style.color=c?.value==='rainbow'?'#fff':c?.value||'#fff';if(c?.value==='rainbow'){p.style.background='none';p.style.backgroundSize='';p.style.webkitBackgroundClip='';p.style.backgroundClip=''}else{p.style.background='';p.style.backgroundSize='';p.style.webkitBackgroundClip='';p.style.backgroundClip=''}}
 ['customizeName','customizeColor','customizeEffect'].forEach(id=>$(id)?.addEventListener('input',updatePreview));
 $('customizeSave')?.addEventListener('click',async()=>{const a=getAuth(),err=$('customizeError');if(!a)return;err.textContent='';try{const r=await fetch('/api/profile/customize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:a.id,token:a.token,visualName:$('customizeName').value,color:$('customizeColor').value,effect:$('customizeEffect').value})}),d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível guardar.');localStorage.setItem('eixo_player',JSON.stringify({...player(),...d.player,token:a.token}));window.dispatchEvent(new Event('eixo-player-updated'));close('customizeModal');if(window.eixoRefreshRankings)window.eixoRefreshRankings();}catch(e){err.textContent=e.message}});
 function addRoomEntryButtons(){const list=$('roomsList');if(!list)return;list.querySelectorAll('.room-item').forEach(item=>{if(item.querySelector('.enter-room-button'))return;const roomId=item.dataset.roomId||item.getAttribute('data-room-id');if(!roomId)return;const b=document.createElement('button');b.type='button';b.className='board-more enter-room-button';b.textContent=window.eixoT?window.eixoT('enterRoom','ENTRAR NA SALA'):'ENTRAR NA SALA';b.addEventListener('click',()=>openRoom(roomId));item.appendChild(b);});}
 const roomsList=$('roomsList');if(roomsList)new MutationObserver(addRoomEntryButtons).observe(roomsList,{childList:true,subtree:true});
 async function openRoom(roomId){const a=getAuth();if(!a)return;try{const r=await fetch(`/api/rooms/rankings?id=${encodeURIComponent(a.id)}&token=${encodeURIComponent(a.token)}&roomId=${encodeURIComponent(roomId)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Sala indisponível');const room=[...document.querySelectorAll('.room-item')].find(x=>(x.dataset.roomId||x.getAttribute('data-room-id'))===roomId);$('roomBoardTitle').textContent=room?.querySelector('.room-item-name')?.textContent||(window.eixoT?window.eixoT('room','SALA'):'SALA');$('roomBoardMeta').textContent=` · ${d.players.length} ${window.eixoT?window.eixoT('players','JOGADORES'):'JOGADORES'}`;renderRoom(d.players);$('roomBoard').classList.remove('hidden');close('roomsModal');document.getElementById('roomBoard').scrollIntoView({behavior:'smooth',block:'start'});window.eixoActiveRoomId=roomId;}catch(e){alert(e.message)}}
 function renderRoom(players){list=document.getElementById('roomRanking');list.innerHTML=players.map(p=>{const f=[...String(p.country||'')].map(c=>String.fromCodePoint(127397+c.charCodeAt())).join('');const color=p.nameColor||'#fff';const rainbow=color==='rainbow';const styles=Array.isArray(p.letterStyles)?p.letterStyles:[];const name=[...String(p.visualName||p.name)].map((ch,i)=>{const s=styles[i]||{};const sc=/^#[0-9a-f]{6}$/i.test(String(s.color||''))?s.color:'';const ef=/^[a-z]+$/.test(String(s.effect||''))?s.effect:'none';return \`<span class="name-letter effect-\${ef}" style="\${sc?'color:'+esc(sc)+';':''}">\${esc(ch)}</span>\`}).join('');return \`<li><span class="rank-number">\${p.roomRank}</span><span class="rank-name-wrap"><span class="rank-flag" title="\${esc(p.country)}">\${esc(f)}</span><span class="rank-player-name \${effectClass(p.nameEffect)}\${rainbow?' name-rainbow':''}">\${styles.length?name:\`<span class="name-letter">\${esc(p.visualName||p.name)}</span>\`}</span></span><span class="rank-score">\${Number(p.score||0)}</span></li>\`}).join('')||\`<li class="empty-row">\${window.eixoT?window.eixoT('emptyRanking','AINDA SEM JOGADORES'):'AINDA SEM JOGADORES'}</li>\`;}

 $('leaveActiveRoom')?.addEventListener('click',async()=>{const a=getAuth(),id=window.eixoActiveRoomId;if(!a||!id)return;await fetch('/api/rooms/leave',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:a.id,token:a.token,roomId:id})});window.eixoActiveRoomId=null;$('roomBoard').classList.add('hidden');if(typeof window.eixoRefreshRankings==='function')window.eixoRefreshRankings();});
 setInterval(async()=>{if(!window.eixoActiveRoomId)return;const a=getAuth();if(!a)return;try{const r=await fetch(`/api/rooms/rankings?id=${encodeURIComponent(a.id)}&token=${encodeURIComponent(a.token)}&roomId=${encodeURIComponent(window.eixoActiveRoomId)}`,{cache:'no-store'});if(r.ok){const d=await r.json();renderRoom(d.players);$('roomBoardMeta').textContent=` · ${d.players.length} ${window.eixoT?window.eixoT('players','JOGADORES'):'JOGADORES'}`}}catch(_){ }},3000);
})();
