/* EIXO extended native-language locales for countries that previously fell back to English. */
(function(){
  const make=(o)=>{
    const c=o.core,f=o.form||{};
    const forms={
      close:f.close||'CLOSE',
      onboardingTitle:c.welcome,onboardingText:c.countryIntro,country:c.country,continue:c.continue,
      nameTitle:c.nameTitle,nameText:c.nameText,nameLabel:c.nameLabel,nameRules:f.nameRules,create:c.create,
      contactTitle:f.contactTitle,contactText:f.contactText,name:f.name,email:'EMAIL',subject:f.subject,message:f.message,send:f.send,
      bugsTitle:f.bugsTitle,bugsText:f.bugsText,bugSubject:f.bugSubject,bugMessage:f.bugMessage,sendBug:f.sendBug,
      customizeTitle:f.customizeTitle,customizeHint:f.customizeHint,visualName:f.visualName,nameColor:f.nameColor,effect:f.effect,save:f.save,
      worldTab:f.worldTab,loading:f.loading,emptyRanking:f.emptyRanking,emptyFull:f.emptyFull,players:f.players,
      leaveRoom:f.leaveRoom,enterRoom:f.enterRoom,room:f.room,messageSent:f.messageSent
    };
    return {...o,forms};
  };
  const L={

ms:make({
 core:{play:"MAIN",ranking:"KEDUDUKAN",rooms:"BILIK",about:"TENTANG",myRooms:"BILIK SAYA",instruction:"KLIK APABILA TITIK BERADA DI TENGAH",worldTop:"KEDUDUKAN DUNIA",fullRanking:"LIHAT KEDUDUKAN PENUH",aboutText:" — permainan refleks ringkas. Tepat di tengah, kumpul mata dan naik kedudukan.",welcome:"SELAMAT DATANG KE EIXO",countryIntro:"Pilih negara anda dahulu.",country:"NEGARA",continue:"TERUSKAN",nameTitle:"PILIH NAMA ANDA",nameText:"Nama ini akan dikaitkan dengan pemain anda dan tidak boleh digunakan oleh orang lain.",nameLabel:"NAMA PEMAIN",create:"CIPTA PEMAIN",nameInvalid:"Gunakan 3–8 huruf atau nombor tanpa ruang atau simbol.",nameTaken:"Nama ini telah digunakan."},
 form:{close:"TUTUP",nameRules:"3–8 AKSARA · HURUF DAN NOMBOR · TIADA RUANG ATAU SIMBOL",contactTitle:"HUBUNGI",contactText:"Pengiklanan, kerjasama, maklumat atau pertanyaan lain.",name:"NAMA",subject:"SUBJEK",message:"MESEJ",send:"HANTAR ▶",bugsTitle:"LAPOR BUG",bugsText:"Hantar butiran supaya kami boleh menghasilkan semula dan membaiki masalah.",bugSubject:"TAJUK BUG",bugMessage:"TERANGKAN BUG, APA YANG ANDA LAKUKAN DAN APA YANG BERLAKU",sendBug:"HANTAR BUG ▶",customizeTitle:"SESUAIKAN NAMA",customizeHint:"Pilihan yang tersedia bergantung pada kedudukan anda.",visualName:"NAMA PAPARAN",nameColor:"WARNA NAMA",effect:"KESAN",save:"SIMPAN ▶",worldTab:"🌐 DUNIA",loading:"MEMUAT...",emptyRanking:"BELUM ADA PEMAIN",emptyFull:"BELUM ADA PEMAIN",players:"PEMAIN",leaveRoom:"TINGGALKAN BILIK",enterRoom:"MASUK BILIK",room:"BILIK",messageSent:"Mesej dihantar. Terima kasih!"},
 menu:{settings:"TETAPAN",customize:"SESUAIKAN NAMA",bugs:"LAPOR BUG",suggestions:"CADANGAN",contact:"HUBUNGI",logout:"LOG KELUAR",vipSoon:"VIP — AKAN DATANG",vipCustomize:"SESUAIKAN NAMA VIP",signIn:"LOG MASUK"},
 rooms:{createRoom:"CIPTA BILIK",createRoomTitle:"CIPTA BILIK",roomName:"NAMA BILIK",players:"PEMAIN",create:"CIPTA BILIK",roomCreated:"BILIK DICIPTA",shareCode:"Kongsi kod ini dengan rakan supaya mereka boleh menyertai.",copyCode:"SALIN KOD",copied:"KOD DISALIN",myRoomsTitle:"BILIK SAYA",addRoom:"TAMBAH BILIK",roomCode:"KOD BILIK",join:"SERTAI",loading:"MEMUAT...",empty:"ANDA BELUM MENYERTAI MANA-MANA BILIK.",full:"PENUH",playersLabel:"PEMAIN",invalidName:"Nama bilik tidak sah.",invalidCode:"Kod tidak sah.",notFound:"Bilik tidak ditemui.",fullError:"Bilik ini sudah penuh.",createdError:"Bilik tidak dapat dicipta."},
 chat:{title:"SEMBANG",global:"GLOBAL",all:"SEMUA PEMAIN",only:"HANYA",write:"TULIS MESEJ...",writeN:"TULIS UNTUK NEGARA ANDA...",hint:"MAKS. 300 AKSARA · ELAK SPAM",empty:"BELUM ADA MESEJ.<br>JADILAH YANG PERTAMA.",need:"CIPTA PEMAIN UNTUK MENGGUNAKAN SEMBANG.",sending:"MENGHANTAR..."},
 misc:{close:"TUTUP",suggestionTitle:"CADANGAN",suggestionText:"Kongsi idea untuk menambah baik EIXO. Cadangan boleh membantu membentuk kemas kini akan datang.",suggestionSubject:"TAJUK CADANGAN",suggestionMessage:"TERANGKAN CADANGAN ANDA",suggestionSend:"HANTAR CADANGAN",abandonTitle:"TINGGALKAN BILIK",abandonQuestion:"Adakah anda pasti mahu meninggalkan bilik ini?",abandonWarning:"Anda akan dikeluarkan dari bilik. Untuk menyertai semula, anda memerlukan kod bilik.",no:"TIDAK",yes:"YA",prev:"SEBELUM",next:"SETERUSNYA",leave:"TINGGALKAN BILIK",abandon:"TINGGALKAN BILIK"},
 account:{title:"TETAPAN AKAUN",name:"NAMA",avatar:"AVATAR",border:"BINGKAI AVATAR",save:"SIMPAN",close:"TUTUP",saved:"TETAPAN DISIMPAN.",admin:"PENTADBIRAN",playerName:"PEMAIN (NAMA)",vip:"VIP 0–6",role:"PERANAN",moderator:"MODERATOR",player:"PEMAIN",setVip:"TETAPKAN VIP",setRole:"TETAPKAN PERANAN",kick:"KELUARKAN",ban24:"SEKAT 24J",banPermanent:"SEKAT KEKAL",moderation:"MODERASI",done:"TINDAKAN SELESAI."},
 vip:{close:"TUTUP",statusNone:"Anda belum mempunyai VIP.",statusLevel:"Anda mempunyai VIP #{n}. VIP adalah kekal.",statusInf:"Anda mempunyai VIP ∞. Sokongan boleh diteruskan tanpa had.",benefitsTitle:"KELEBIHAN VIP",benefits:["Nama paparan dengan ruang dan aksara khas","Warna dan animasi berasingan bagi setiap aksara","10 warna eksklusif VIP","Bilik peribadi lebih besar mengikut tahap","TAG VIP kekal pada akaun"],buy:"BELI VIP {n} (UJIAN)",buyInf:"BELI VIP ∞ (UJIAN)",activateError:"VIP tidak dapat diaktifkan.",customizeTitle:"SESUAIKAN NAMA VIP",customizeDesc:"Nama paparan boleh menggunakan ruang, simbol dan aksara khas. Setiap aksara boleh mempunyai warna dan animasi sendiri.",visualName:"NAMA PAPARAN VIP",letter:"AKSARA",color:"WARNA",effect:"KESAN",worldTag:"WARNA TAG DUNIA",countryTag:"WARNA TAG NEGARA",save:"SIMPAN",lockOn:"VIP ∞ — pilih warna berbeza untuk setiap TAG.",lockOff:"VIP ∞ SAHAJA — capai tahap akhir untuk menyesuaikan warna TAG.",player:"PEMAIN",saveError:"Tidak dapat menyimpan."}
}),

uk:make({
 core:{play:"ГРАТИ",ranking:"РЕЙТИНГ",rooms:"КІМНАТИ",about:"ПРО ГРУ",myRooms:"МОЇ КІМНАТИ",instruction:"НАТИСНИ, КОЛИ ТОЧКА БУДЕ В ЦЕНТРІ",worldTop:"СВІТОВИЙ РЕЙТИНГ",fullRanking:"ПОВНИЙ РЕЙТИНГ",aboutText:" — проста гра на реакцію. Влучай у центр, набирай очки та піднімайся в рейтингу.",welcome:"ЛАСКАВО ПРОСИМО ДО EIXO",countryIntro:"Спочатку вибери свою країну.",country:"КРАЇНА",continue:"ПРОДОВЖИТИ",nameTitle:"ОБЕРИ ІМ’Я",nameText:"Це ім’я буде пов’язане з твоїм гравцем і не зможе використовуватися іншими.",nameLabel:"ІМ’Я ГРАВЦЯ",create:"СТВОРИТИ ГРАВЦЯ",nameInvalid:"Використовуй 3–8 літер або цифр без пробілів і символів.",nameTaken:"Це ім’я вже використовується."},
 form:{close:"ЗАКРИТИ",nameRules:"3–8 СИМВОЛІВ · ЛІТЕРИ Й ЦИФРИ · БЕЗ ПРОБІЛІВ І ЗНАКІВ",contactTitle:"КОНТАКТ",contactText:"Реклама, партнерства, інформація або інші питання.",name:"ІМ’Я",subject:"ТЕМА",message:"ПОВІДОМЛЕННЯ",send:"НАДІСЛАТИ ▶",bugsTitle:"ПОВІДОМИТИ ПРО ПОМИЛКУ",bugsText:"Надішли деталі, щоб ми могли відтворити й виправити проблему.",bugSubject:"НАЗВА ПОМИЛКИ",bugMessage:"ОПИШИ ПОМИЛКУ, ЩО ТИ РОБИВ І ЩО СТАЛОСЯ",sendBug:"НАДІСЛАТИ ▶",customizeTitle:"НАЛАШТУВАТИ ІМ’Я",customizeHint:"Доступні параметри залежать від твоєї позиції в рейтингу.",visualName:"ВІДОБРАЖУВАНЕ ІМ’Я",nameColor:"КОЛІР ІМЕНІ",effect:"ЕФЕКТ",save:"ЗБЕРЕГТИ ▶",worldTab:"🌐 СВІТ",loading:"ЗАВАНТАЖЕННЯ...",emptyRanking:"ГРАВЦІВ ЩЕ НЕМАЄ",emptyFull:"ГРАВЦІВ ЩЕ НЕМАЄ",players:"ГРАВЦІ",leaveRoom:"ВИЙТИ З КІМНАТИ",enterRoom:"УВІЙТИ ДО КІМНАТИ",room:"КІМНАТА",messageSent:"Повідомлення надіслано. Дякуємо!"},
 menu:{settings:"НАЛАШТУВАННЯ",customize:"НАЛАШТУВАТИ ІМ’Я",bugs:"ПОВІДОМИТИ ПРО ПОМИЛКУ",suggestions:"ПРОПОЗИЦІЇ",contact:"КОНТАКТ",logout:"ВИЙТИ",vipSoon:"VIP — НЕЗАБАРОМ",vipCustomize:"НАЛАШТУВАТИ VIP-ІМ’Я",signIn:"УВІЙТИ"},
 rooms:{createRoom:"СТВОРИТИ КІМНАТУ",createRoomTitle:"СТВОРИТИ КІМНАТУ",roomName:"НАЗВА КІМНАТИ",players:"ГРАВЦІ",create:"СТВОРИТИ",roomCreated:"КІМНАТУ СТВОРЕНО",shareCode:"Передай цей код друзям, щоб вони могли приєднатися.",copyCode:"КОПІЮВАТИ КОД",copied:"КОД СКОПІЙОВАНО",myRoomsTitle:"МОЇ КІМНАТИ",addRoom:"ДОДАТИ КІМНАТУ",roomCode:"КОД КІМНАТИ",join:"ПРИЄДНАТИСЯ",loading:"ЗАВАНТАЖЕННЯ...",empty:"ТИ ЩЕ НЕ В ЖОДНІЙ КІМНАТІ.",full:"ЗАПОВНЕНА",playersLabel:"ГРАВЦІ",invalidName:"Невірна назва кімнати.",invalidCode:"Невірний код.",notFound:"Кімнату не знайдено.",fullError:"Кімната вже заповнена.",createdError:"Не вдалося створити кімнату."},
 chat:{title:"ЧАТ",global:"ГЛОБАЛЬНИЙ",all:"УСІ ГРАВЦІ",only:"ЛИШЕ",write:"НАПИШИ ПОВІДОМЛЕННЯ...",writeN:"НАПИШИ ДЛЯ СВОЄЇ КРАЇНИ...",hint:"МАКС. 300 СИМВОЛІВ · БЕЗ СПАМУ",empty:"ПОВІДОМЛЕНЬ ЩЕ НЕМАЄ.<br>БУДЬ ПЕРШИМ.",need:"СТВОРИ ГРАВЦЯ, ЩОБ КОРИСТУВАТИСЯ ЧАТОМ.",sending:"НАДСИЛАННЯ..."},
 misc:{close:"ЗАКРИТИ",suggestionTitle:"ПРОПОЗИЦІЇ",suggestionText:"Поділися ідеєю, як покращити EIXO. Пропозиції можуть впливати на майбутні оновлення.",suggestionSubject:"НАЗВА ПРОПОЗИЦІЇ",suggestionMessage:"ОПИШИ СВОЮ ПРОПОЗИЦІЮ",suggestionSend:"НАДІСЛАТИ ПРОПОЗИЦІЮ",abandonTitle:"ПОКИНУТИ КІМНАТУ",abandonQuestion:"Точно хочеш покинути цю кімнату?",abandonWarning:"Тебе буде видалено з кімнати. Для повторного входу знадобиться код кімнати.",no:"НІ",yes:"ТАК",prev:"НАЗАД",next:"ДАЛІ",leave:"ВИЙТИ З КІМНАТИ",abandon:"ПОКИНУТИ КІМНАТУ"},
 account:{title:"НАЛАШТУВАННЯ ОБЛІКОВОГО ЗАПИСУ",name:"ІМ’Я",avatar:"АВАТАР",border:"РАМКА АВАТАРА",save:"ЗБЕРЕГТИ",close:"ЗАКРИТИ",saved:"НАЛАШТУВАННЯ ЗБЕРЕЖЕНО.",admin:"АДМІНІСТРУВАННЯ",playerName:"ГРАВЕЦЬ (ІМ’Я)",vip:"VIP 0–6",role:"РОЛЬ",moderator:"МОДЕРАТОР",player:"ГРАВЕЦЬ",setVip:"ВСТАНОВИТИ VIP",setRole:"ВСТАНОВИТИ РОЛЬ",kick:"ВИКЛЮЧИТИ",ban24:"БАН 24Г",banPermanent:"ПОСТІЙНИЙ БАН",moderation:"МОДЕРАЦІЯ",done:"ДІЮ ВИКОНАНО."},
 vip:{close:"ЗАКРИТИ",statusNone:"У тебе ще немає VIP.",statusLevel:"У тебе VIP #{n}. VIP постійний.",statusInf:"У тебе VIP ∞. Підтримка може тривати без обмежень.",benefitsTitle:"ПЕРЕВАГИ VIP",benefits:["Відображуване ім’я з пробілами та спецсимволами","Окремі кольори й анімації для кожного символу","10 ексклюзивних VIP-кольорів","Більші приватні кімнати залежно від рівня","VIP-тег назавжди залишається в акаунті"],buy:"КУПИТИ VIP {n} (ТЕСТ)",buyInf:"КУПИТИ VIP ∞ (ТЕСТ)",activateError:"Не вдалося активувати VIP.",customizeTitle:"НАЛАШТУВАТИ VIP-ІМ’Я",customizeDesc:"Відображуване ім’я може містити пробіли, символи та спеціальні знаки. Кожен символ може мати власний колір і анімацію.",visualName:"VIP-ІМ’Я",letter:"СИМВОЛ",color:"КОЛІР",effect:"ЕФЕКТ",worldTag:"КОЛІР СВІТОВОГО ТЕГА",countryTag:"КОЛІР НАЦІОНАЛЬНОГО ТЕГА",save:"ЗБЕРЕГТИ",lockOn:"VIP ∞ — обери окремий колір для кожного тега.",lockOff:"ЛИШЕ VIP ∞ — досягни останнього рівня для налаштування тегів.",player:"ГРАВЕЦЬ",saveError:"Не вдалося зберегти."}
}),

sk:make({
 core:{play:"HRAŤ",ranking:"REBRÍČEK",rooms:"MIESTNOSTI",about:"O HRE",myRooms:"MOJE MIESTNOSTI",instruction:"KLIKNI, KEĎ JE BOD V STREDE",worldTop:"SVETOVÝ REBRÍČEK",fullRanking:"ZOBRAZIŤ CELÝ REBRÍČEK",aboutText:" — jednoduchá reflexná hra. Traf stred, získavaj body a stúpaj v rebríčku.",welcome:"VITAJ V EIXO",countryIntro:"Najprv si vyber svoju krajinu.",country:"KRAJINA",continue:"POKRAČOVAŤ",nameTitle:"VYBER SI MENO",nameText:"Toto meno bude spojené s tvojím hráčom a nikto iný ho nebude môcť použiť.",nameLabel:"MENO HRÁČA",create:"VYTVORIŤ HRÁČA",nameInvalid:"Použi 3–8 písmen alebo číslic bez medzier a symbolov.",nameTaken:"Toto meno sa už používa."},
 form:{close:"ZAVRIEŤ",nameRules:"3–8 ZNAKOV · PÍSMENÁ A ČÍSLA · BEZ MEDZIER A SYMBOLOV",contactTitle:"KONTAKT",contactText:"Reklama, partnerstvá, informácie alebo iné otázky.",name:"MENO",subject:"PREDMET",message:"SPRÁVA",send:"ODOSLAŤ ▶",bugsTitle:"NAHLÁSIŤ CHYBU",bugsText:"Pošli podrobnosti, aby sme mohli problém zopakovať a opraviť.",bugSubject:"NÁZOV CHYBY",bugMessage:"OPÍŠ CHYBU, ČO SI UROBIL A ČO SA STALO",sendBug:"ODOSLAŤ CHYBU ▶",customizeTitle:"PRISPÔSOBIŤ MENO",customizeHint:"Dostupné možnosti závisia od tvojej pozície v rebríčku.",visualName:"ZOBRAZOVANÉ MENO",nameColor:"FARBA MENA",effect:"EFEKT",save:"ULOŽIŤ ▶",worldTab:"🌐 SVET",loading:"NAČÍTAVA SA...",emptyRanking:"ZATIAĽ ŽIADNI HRÁČI",emptyFull:"ZATIAĽ ŽIADNI HRÁČI",players:"HRÁČI",leaveRoom:"OPUSTIŤ MIESTNOSŤ",enterRoom:"VSTÚPIŤ DO MIESTNOSTI",room:"MIESTNOSŤ",messageSent:"Správa bola odoslaná. Ďakujeme!"},
 menu:{settings:"NASTAVENIA",customize:"PRISPÔSOBIŤ MENO",bugs:"NAHLÁSIŤ CHYBU",suggestions:"NÁVRHY",contact:"KONTAKT",logout:"ODHLÁSIŤ",vipSoon:"VIP — UŽ ČOSKORO",vipCustomize:"PRISPÔSOBIŤ VIP MENO",signIn:"PRIHLÁSIŤ"},
 rooms:{createRoom:"VYTVORIŤ MIESTNOSŤ",createRoomTitle:"VYTVORIŤ MIESTNOSŤ",roomName:"NÁZOV MIESTNOSTI",players:"HRÁČI",create:"VYTVORIŤ",roomCreated:"MIESTNOSŤ VYTVORENÁ",shareCode:"Zdieľaj tento kód s priateľmi, aby sa mohli pripojiť.",copyCode:"KOPÍROVAŤ KÓD",copied:"KÓD SKOPÍROVANÝ",myRoomsTitle:"MOJE MIESTNOSTI",addRoom:"PRIDAŤ MIESTNOSŤ",roomCode:"KÓD MIESTNOSTI",join:"PRIPOJIŤ SA",loading:"NAČÍTAVA SA...",empty:"ZATIAĽ NIE SI V ŽIADNEJ MIESTNOSTI.",full:"PLNÁ",playersLabel:"HRÁČI",invalidName:"Neplatný názov miestnosti.",invalidCode:"Neplatný kód.",notFound:"Miestnosť sa nenašla.",fullError:"Táto miestnosť je plná.",createdError:"Miestnosť sa nepodarilo vytvoriť."},
 chat:{title:"CHAT",global:"GLOBÁLNY",all:"VŠETCI HRÁČI",only:"IBA",write:"NAPÍŠ SPRÁVU...",writeN:"NAPÍŠ PRE SVOJU KRAJINU...",hint:"MAX. 300 ZNAKOV · BEZ SPAMU",empty:"ZATIAĽ ŽIADNE SPRÁVY.<br>BUĎ PRVÝ.",need:"VYTVOR HRÁČA, ABY SI MOHOL POUŽÍVAŤ CHAT.",sending:"ODOSIELA SA..."},
 misc:{close:"ZAVRIEŤ",suggestionTitle:"NÁVRHY",suggestionText:"Podeľ sa o nápad na zlepšenie EIXO. Návrhy môžu pomôcť formovať budúce aktualizácie.",suggestionSubject:"NÁZOV NÁVRHU",suggestionMessage:"OPÍŠ SVOJ NÁVRH",suggestionSend:"ODOSLAŤ NÁVRH",abandonTitle:"OPUSTIŤ MIESTNOSŤ",abandonQuestion:"Naozaj chceš opustiť túto miestnosť?",abandonWarning:"Budeš z miestnosti odstránený. Na opätovný vstup budeš potrebovať kód miestnosti.",no:"NIE",yes:"ÁNO",prev:"PREDCHÁDZAJÚCA",next:"ĎALŠIA",leave:"OPUSTIŤ MIESTNOSŤ",abandon:"OPUSTIŤ MIESTNOSŤ"},
 account:{title:"NASTAVENIA ÚČTU",name:"MENO",avatar:"AVATAR",border:"RÁMIK AVATARU",save:"ULOŽIŤ",close:"ZAVRIEŤ",saved:"NASTAVENIA ULOŽENÉ.",admin:"ADMINISTRÁCIA",playerName:"HRÁČ (MENO)",vip:"VIP 0–6",role:"ROLA",moderator:"MODERÁTOR",player:"HRÁČ",setVip:"NASTAVIŤ VIP",setRole:"NASTAVIŤ ROLU",kick:"VYHODIŤ",ban24:"BAN 24H",banPermanent:"TRVALÝ BAN",moderation:"MODERÁCIA",done:"AKCIA DOKONČENÁ."},
 vip:{close:"ZAVRIEŤ",statusNone:"VIP zatiaľ nemáš.",statusLevel:"Máš VIP #{n}. VIP je trvalé.",statusInf:"Máš VIP ∞. Podpora môže pokračovať bez obmedzení.",benefitsTitle:"VIP VÝHODY",benefits:["Zobrazované meno s medzerami a špeciálnymi znakmi","Samostatné farby a animácie pre každý znak","10 exkluzívnych VIP farieb","Väčšie súkromné miestnosti podľa úrovne","VIP značka zostáva na účte natrvalo"],buy:"KÚPIŤ VIP {n} (TEST)",buyInf:"KÚPIŤ VIP ∞ (TEST)",activateError:"VIP sa nepodarilo aktivovať.",customizeTitle:"PRISPÔSOBIŤ VIP MENO",customizeDesc:"Zobrazované meno môže obsahovať medzery, symboly a špeciálne znaky. Každý znak môže mať vlastnú farbu a animáciu.",visualName:"VIP ZOBRAZOVANÉ MENO",letter:"ZNAK",color:"FARBA",effect:"EFEKT",worldTag:"FARBA SVETOVEJ ZNAČKY",countryTag:"FARBA NÁRODNEJ ZNAČKY",save:"ULOŽIŤ",lockOn:"VIP ∞ — vyber inú farbu pre každú značku.",lockOff:"IBA VIP ∞ — dosiahni poslednú úroveň na úpravu značiek.",player:"HRÁČ",saveError:"Nepodarilo sa uložiť."}
}),

hu:make({
 core:{play:"JÁTÉK",ranking:"RANGLISTA",rooms:"SZOBÁK",about:"NÉVJEGY",myRooms:"SZOBÁIM",instruction:"KATTINTS, AMIKOR A PONT KÖZÉPEN VAN",worldTop:"VILÁGRANGLISTA",fullRanking:"TELJES RANGLISTA",aboutText:" — egyszerű reflexjáték. Találd el a közepét, szerezz pontokat és lépj feljebb a ranglistán.",welcome:"ÜDVÖZLÜNK AZ EIXO-BAN",countryIntro:"Először válaszd ki az országodat.",country:"ORSZÁG",continue:"TOVÁBB",nameTitle:"VÁLASSZ NEVET",nameText:"Ez a név a játékosodhoz lesz kötve, és más nem használhatja.",nameLabel:"JÁTÉKOSNÉV",create:"JÁTÉKOS LÉTREHOZÁSA",nameInvalid:"Használj 3–8 betűt vagy számot szóköz és szimbólum nélkül.",nameTaken:"Ez a név már foglalt."},
 form:{close:"BEZÁRÁS",nameRules:"3–8 KARAKTER · BETŰK ÉS SZÁMOK · NINCS SZÓKÖZ VAGY SZIMBÓLUM",contactTitle:"KAPCSOLAT",contactText:"Hirdetés, partnerség, információ vagy más kérdés.",name:"NÉV",subject:"TÁRGY",message:"ÜZENET",send:"KÜLDÉS ▶",bugsTitle:"HIBA JELENTÉSE",bugsText:"Küldd el a részleteket, hogy reprodukálni és javítani tudjuk a hibát.",bugSubject:"HIBA CÍME",bugMessage:"ÍRD LE A HIBÁT, MIT CSINÁLTÁL ÉS MI TÖRTÉNT",sendBug:"HIBA KÜLDÉSE ▶",customizeTitle:"NÉV TESTRESZABÁSA",customizeHint:"Az elérhető lehetőségek a ranglistás helyezésedtől függenek.",visualName:"MEGJELENÍTETT NÉV",nameColor:"NÉV SZÍNE",effect:"EFFEKT",save:"MENTÉS ▶",worldTab:"🌐 VILÁG",loading:"BETÖLTÉS...",emptyRanking:"MÉG NINCSENEK JÁTÉKOSOK",emptyFull:"MÉG NINCSENEK JÁTÉKOSOK",players:"JÁTÉKOSOK",leaveRoom:"SZOBA ELHAGYÁSA",enterRoom:"BELÉPÉS A SZOBÁBA",room:"SZOBA",messageSent:"Üzenet elküldve. Köszönjük!"},
 menu:{settings:"BEÁLLÍTÁSOK",customize:"NÉV TESTRESZABÁSA",bugs:"HIBA JELENTÉSE",suggestions:"JAVASLATOK",contact:"KAPCSOLAT",logout:"KIJELENTKEZÉS",vipSoon:"VIP — HAMAROSAN",vipCustomize:"VIP-NÉV TESTRESZABÁSA",signIn:"BEJELENTKEZÉS"},
 rooms:{createRoom:"SZOBA LÉTREHOZÁSA",createRoomTitle:"SZOBA LÉTREHOZÁSA",roomName:"SZOBA NEVE",players:"JÁTÉKOSOK",create:"LÉTREHOZÁS",roomCreated:"SZOBA LÉTREHOZVA",shareCode:"Add át ezt a kódot a barátaidnak a csatlakozáshoz.",copyCode:"KÓD MÁSOLÁSA",copied:"KÓD MÁSOLVA",myRoomsTitle:"SZOBÁIM",addRoom:"SZOBA HOZZÁADÁSA",roomCode:"SZOBAKÓD",join:"CSATLAKOZÁS",loading:"BETÖLTÉS...",empty:"MÉG NEM VAGY EGY SZOBÁBAN SEM.",full:"TELE",playersLabel:"JÁTÉKOSOK",invalidName:"Érvénytelen szobanév.",invalidCode:"Érvénytelen kód.",notFound:"A szoba nem található.",fullError:"Ez a szoba megtelt.",createdError:"A szobát nem sikerült létrehozni."},
 chat:{title:"CHAT",global:"GLOBÁLIS",all:"MINDEN JÁTÉKOS",only:"CSAK",write:"ÍRJ ÜZENETET...",writeN:"ÍRJ AZ ORSZÁGODNAK...",hint:"MAX. 300 KARAKTER · NE SPAMELJ",empty:"MÉG NINCS ÜZENET.<br>LÉGY TE AZ ELSŐ.",need:"HOZZ LÉTRE JÁTÉKOST A CHAT HASZNÁLATÁHOZ.",sending:"KÜLDÉS..."},
 misc:{close:"BEZÁRÁS",suggestionTitle:"JAVASLATOK",suggestionText:"Oszd meg az ötletedet az EIXO fejlesztéséhez. A javaslatok segíthetnek a jövőbeli frissítések alakításában.",suggestionSubject:"JAVASLAT CÍME",suggestionMessage:"ÍRD LE A JAVASLATODAT",suggestionSend:"JAVASLAT KÜLDÉSE",abandonTitle:"SZOBA ELHAGYÁSA",abandonQuestion:"Biztosan elhagyod ezt a szobát?",abandonWarning:"Eltávolítunk a szobából. Az újbóli belépéshez szükséged lesz a szobakódra.",no:"NEM",yes:"IGEN",prev:"ELŐZŐ",next:"KÖVETKEZŐ",leave:"SZOBA ELHAGYÁSA",abandon:"SZOBA ELHAGYÁSA"},
 account:{title:"FIÓKBEÁLLÍTÁSOK",name:"NÉV",avatar:"AVATAR",border:"AVATAR KERETE",save:"MENTÉS",close:"BEZÁRÁS",saved:"BEÁLLÍTÁSOK MENTVE.",admin:"ADMINISZTRÁCIÓ",playerName:"JÁTÉKOS (NÉV)",vip:"VIP 0–6",role:"SZEREPKÖR",moderator:"MODERÁTOR",player:"JÁTÉKOS",setVip:"VIP BEÁLLÍTÁSA",setRole:"SZEREPKÖR BEÁLLÍTÁSA",kick:"KIRÚGÁS",ban24:"24 ÓRÁS TILTÁS",banPermanent:"VÉGLEGES TILTÁS",moderation:"MODERÁCIÓ",done:"MŰVELET KÉSZ."},
 vip:{close:"BEZÁRÁS",statusNone:"Még nincs VIP-od.",statusLevel:"VIP #{n} szinted van. A VIP végleges.",statusInf:"VIP ∞ szinted van. A támogatás korlátlanul folytatódhat.",benefitsTitle:"VIP ELŐNYÖK",benefits:["Megjelenített név szóközökkel és speciális karakterekkel","Külön színek és animációk karakterenként","10 exkluzív VIP-szín","Nagyobb privát szobák szinttől függően","A VIP címke végleg a fiókban marad"],buy:"VIP {n} VÁSÁRLÁSA (TESZT)",buyInf:"VIP ∞ VÁSÁRLÁSA (TESZT)",activateError:"A VIP aktiválása sikertelen.",customizeTitle:"VIP-NÉV TESTRESZABÁSA",customizeDesc:"A megjelenített név tartalmazhat szóközöket, szimbólumokat és speciális karaktereket. Minden karakternek saját színe és animációja lehet.",visualName:"VIP MEGJELENÍTETT NÉV",letter:"KARAKTER",color:"SZÍN",effect:"EFFEKT",worldTag:"VILÁG CÍMKE SZÍNE",countryTag:"ORSZÁG CÍMKE SZÍNE",save:"MENTÉS",lockOn:"VIP ∞ — válassz más színt minden címkéhez.",lockOff:"CSAK VIP ∞ — érd el az utolsó szintet a címkék testreszabásához.",player:"JÁTÉKOS",saveError:"Nem sikerült menteni."}
}),

ro:make({
 core:{play:"JOACĂ",ranking:"CLASAMENT",rooms:"CAMERE",about:"DESPRE",myRooms:"CAMERELE MELE",instruction:"APASĂ CÂND PUNCTUL ESTE ÎN CENTRU",worldTop:"CLASAMENT MONDIAL",fullRanking:"VEZI CLASAMENTUL COMPLET",aboutText:" — un joc simplu de reflexe. Nimerește centrul, adună puncte și urcă în clasament.",welcome:"BINE AI VENIT LA EIXO",countryIntro:"Mai întâi alege țara.",country:"ȚARĂ",continue:"CONTINUĂ",nameTitle:"ALEGE-ȚI NUMELE",nameText:"Acest nume va fi asociat jucătorului tău și nu va putea fi folosit de altcineva.",nameLabel:"NUME JUCĂTOR",create:"CREEAZĂ JUCĂTOR",nameInvalid:"Folosește 3–8 litere sau cifre, fără spații sau simboluri.",nameTaken:"Acest nume este deja folosit."},
 form:{close:"ÎNCHIDE",nameRules:"3–8 CARACTERE · LITERE ȘI CIFRE · FĂRĂ SPAȚII SAU SIMBOLURI",contactTitle:"CONTACT",contactText:"Publicitate, parteneriate, informații sau alte întrebări.",name:"NUME",subject:"SUBIECT",message:"MESAJ",send:"TRIMITE ▶",bugsTitle:"RAPORTEAZĂ EROARE",bugsText:"Trimite detalii pentru a putea reproduce și remedia problema.",bugSubject:"TITLUL ERORII",bugMessage:"DESCRIE EROAREA, CE AI FĂCUT ȘI CE S-A ÎNTÂMPLAT",sendBug:"TRIMITE EROAREA ▶",customizeTitle:"PERSONALIZEAZĂ NUMELE",customizeHint:"Opțiunile disponibile depind de poziția ta în clasament.",visualName:"NUME AFIȘAT",nameColor:"CULOAREA NUMELUI",effect:"EFECT",save:"SALVEAZĂ ▶",worldTab:"🌐 MONDIAL",loading:"SE ÎNCARCĂ...",emptyRanking:"ÎNCĂ NU SUNT JUCĂTORI",emptyFull:"ÎNCĂ NU SUNT JUCĂTORI",players:"JUCĂTORI",leaveRoom:"PĂRĂSEȘTE CAMERA",enterRoom:"INTRĂ ÎN CAMERĂ",room:"CAMERĂ",messageSent:"Mesaj trimis. Mulțumim!"},
 menu:{settings:"SETĂRI",customize:"PERSONALIZEAZĂ NUMELE",bugs:"RAPORTEAZĂ EROARE",suggestions:"SUGESTII",contact:"CONTACT",logout:"DECONECTARE",vipSoon:"VIP — ÎN CURÂND",vipCustomize:"PERSONALIZEAZĂ NUMELE VIP",signIn:"AUTENTIFICARE"},
 rooms:{createRoom:"CREEAZĂ CAMERĂ",createRoomTitle:"CREEAZĂ O CAMERĂ",roomName:"NUMELE CAMEREI",players:"JUCĂTORI",create:"CREEAZĂ",roomCreated:"CAMERĂ CREATĂ",shareCode:"Dă acest cod prietenilor pentru a se putea alătura.",copyCode:"COPIAZĂ CODUL",copied:"COD COPIAT",myRoomsTitle:"CAMERELE MELE",addRoom:"ADAUGĂ CAMERĂ",roomCode:"COD CAMERĂ",join:"INTRĂ",loading:"SE ÎNCARCĂ...",empty:"NU EȘTI ÎNCĂ ÎN NICIO CAMERĂ.",full:"PLINĂ",playersLabel:"JUCĂTORI",invalidName:"Nume de cameră invalid.",invalidCode:"Cod invalid.",notFound:"Camera nu a fost găsită.",fullError:"Camera este deja plină.",createdError:"Camera nu a putut fi creată."},
 chat:{title:"CHAT",global:"GLOBAL",all:"TOȚI JUCĂTORII",only:"DOAR",write:"SCRIE UN MESAJ...",writeN:"SCRIE PENTRU ȚARA TA...",hint:"MAX. 300 CARACTERE · EVITĂ SPAMUL",empty:"ÎNCĂ NU SUNT MESAJE.<br>FII PRIMUL.",need:"CREEAZĂ UN JUCĂTOR PENTRU A FOLOSI CHATUL.",sending:"SE TRIMITE..."},
 misc:{close:"ÎNCHIDE",suggestionTitle:"SUGESTII",suggestionText:"Împărtășește o idee pentru a îmbunătăți EIXO. Sugestiile pot ajuta la definirea actualizărilor viitoare.",suggestionSubject:"TITLUL SUGESTIEI",suggestionMessage:"DESCRIE SUGESTIA TA",suggestionSend:"TRIMITE SUGESTIA",abandonTitle:"PĂRĂSEȘTE CAMERA",abandonQuestion:"Sigur vrei să părăsești această cameră?",abandonWarning:"Vei fi eliminat din cameră. Pentru a intra din nou, vei avea nevoie de cod.",no:"NU",yes:"DA",prev:"ANTERIOR",next:"URMĂTOR",leave:"PĂRĂSEȘTE CAMERA",abandon:"ABANDONEAZĂ CAMERA"},
 account:{title:"SETĂRI CONT",name:"NUME",avatar:"AVATAR",border:"MARGINE AVATAR",save:"SALVEAZĂ",close:"ÎNCHIDE",saved:"SETĂRI SALVATE.",admin:"ADMINISTRARE",playerName:"JUCĂTOR (NUME)",vip:"VIP 0–6",role:"ROL",moderator:"MODERATOR",player:"JUCĂTOR",setVip:"SETEAZĂ VIP",setRole:"SETEAZĂ ROLUL",kick:"ELIMINĂ",ban24:"BAN 24H",banPermanent:"BAN PERMANENT",moderation:"MODERARE",done:"ACȚIUNE FINALIZATĂ."},
 vip:{close:"ÎNCHIDE",statusNone:"Nu ai încă VIP.",statusLevel:"Ai VIP #{n}. VIP este permanent.",statusInf:"Ai VIP ∞. Sprijinul poate continua fără limită.",benefitsTitle:"BENEFICII VIP",benefits:["Nume afișat cu spații și caractere speciale","Culori și animații independente pentru fiecare caracter","10 culori VIP exclusive","Camere private mai mari în funcție de nivel","Eticheta VIP rămâne permanent pe cont"],buy:"CUMPĂRĂ VIP {n} (TEST)",buyInf:"CUMPĂRĂ VIP ∞ (TEST)",activateError:"VIP nu a putut fi activat.",customizeTitle:"PERSONALIZEAZĂ NUMELE VIP",customizeDesc:"Numele afișat poate folosi spații, simboluri și caractere speciale. Fiecare caracter poate avea propria culoare și animație.",visualName:"NUME AFIȘAT VIP",letter:"CARACTER",color:"CULOARE",effect:"EFECT",worldTag:"CULOARE ETICHETĂ MONDIALĂ",countryTag:"CULOARE ETICHETĂ NAȚIONALĂ",save:"SALVEAZĂ",lockOn:"VIP ∞ — alege o culoare diferită pentru fiecare etichetă.",lockOff:"DOAR VIP ∞ — atinge ultimul nivel pentru a personaliza etichetele.",player:"JUCĂTOR",saveError:"Nu s-a putut salva."}
}),

bg:make({
 core:{play:"ИГРАЙ",ranking:"КЛАСАЦИЯ",rooms:"СТАИ",about:"ЗА ИГРАТА",myRooms:"МОИТЕ СТАИ",instruction:"КЛИКНИ, КОГАТО ТОЧКАТА Е В ЦЕНТЪРА",worldTop:"СВЕТОВНА КЛАСАЦИЯ",fullRanking:"ПЪЛНА КЛАСАЦИЯ",aboutText:" — проста игра за рефлекси. Уцели центъра, печели точки и се изкачвай в класацията.",welcome:"ДОБРЕ ДОШЪЛ В EIXO",countryIntro:"Първо избери държавата си.",country:"ДЪРЖАВА",continue:"ПРОДЪЛЖИ",nameTitle:"ИЗБЕРИ ИМЕ",nameText:"Това име ще бъде свързано с твоя играч и няма да може да се използва от друг.",nameLabel:"ИМЕ НА ИГРАЧ",create:"СЪЗДАЙ ИГРАЧ",nameInvalid:"Използвай 3–8 букви или цифри без интервали и символи.",nameTaken:"Това име вече се използва."},
 form:{close:"ЗАТВОРИ",nameRules:"3–8 ЗНАКА · БУКВИ И ЦИФРИ · БЕЗ ИНТЕРВАЛИ И СИМВОЛИ",contactTitle:"КОНТАКТ",contactText:"Реклама, партньорства, информация или други въпроси.",name:"ИМЕ",subject:"ТЕМА",message:"СЪОБЩЕНИЕ",send:"ИЗПРАТИ ▶",bugsTitle:"ДОКЛАДВАЙ БЪГ",bugsText:"Изпрати подробности, за да можем да възпроизведем и поправим проблема.",bugSubject:"ЗАГЛАВИЕ НА БЪГА",bugMessage:"ОПИШИ БЪГА, КАКВО НАПРАВИ И КАКВО СЕ СЛУЧИ",sendBug:"ИЗПРАТИ БЪГА ▶",customizeTitle:"ПЕРСОНАЛИЗИРАЙ ИМЕ",customizeHint:"Наличните опции зависят от позицията ти в класацията.",visualName:"ПОКАЗВАНО ИМЕ",nameColor:"ЦВЯТ НА ИМЕТО",effect:"ЕФЕКТ",save:"ЗАПАЗИ ▶",worldTab:"🌐 СВЯТ",loading:"ЗАРЕЖДАНЕ...",emptyRanking:"ОЩЕ НЯМА ИГРАЧИ",emptyFull:"ОЩЕ НЯМА ИГРАЧИ",players:"ИГРАЧИ",leaveRoom:"НАПУСНИ СТАЯТА",enterRoom:"ВЛЕЗ В СТАЯТА",room:"СТАЯ",messageSent:"Съобщението е изпратено. Благодаря!"},
 menu:{settings:"НАСТРОЙКИ",customize:"ПЕРСОНАЛИЗИРАЙ ИМЕ",bugs:"ДОКЛАДВАЙ БЪГ",suggestions:"ПРЕДЛОЖЕНИЯ",contact:"КОНТАКТ",logout:"ИЗХОД",vipSoon:"VIP — СКОРО",vipCustomize:"ПЕРСОНАЛИЗИРАЙ VIP ИМЕ",signIn:"ВХОД"},
 rooms:{createRoom:"СЪЗДАЙ СТАЯ",createRoomTitle:"СЪЗДАЙ СТАЯ",roomName:"ИМЕ НА СТАЯТА",players:"ИГРАЧИ",create:"СЪЗДАЙ",roomCreated:"СТАЯТА Е СЪЗДАДЕНА",shareCode:"Дай този код на приятелите си, за да се присъединят.",copyCode:"КОПИРАЙ КОДА",copied:"КОДЪТ Е КОПИРАН",myRoomsTitle:"МОИТЕ СТАИ",addRoom:"ДОБАВИ СТАЯ",roomCode:"КОД НА СТАЯТА",join:"ПРИСЪЕДИНИ СЕ",loading:"ЗАРЕЖДАНЕ...",empty:"ОЩЕ НЕ СИ В НИТО ЕДНА СТАЯ.",full:"ПЪЛНА",playersLabel:"ИГРАЧИ",invalidName:"Невалидно име на стая.",invalidCode:"Невалиден код.",notFound:"Стаята не е намерена.",fullError:"Тази стая вече е пълна.",createdError:"Стаята не можа да бъде създадена."},
 chat:{title:"ЧАТ",global:"ГЛОБАЛЕН",all:"ВСИЧКИ ИГРАЧИ",only:"САМО",write:"НАПИШИ СЪОБЩЕНИЕ...",writeN:"ПИШИ ЗА ТВОЯТА ДЪРЖАВА...",hint:"МАКС. 300 ЗНАКА · БЕЗ СПАМ",empty:"ОЩЕ НЯМА СЪОБЩЕНИЯ.<br>БЪДИ ПЪРВИ.",need:"СЪЗДАЙ ИГРАЧ, ЗА ДА ИЗПОЛЗВАШ ЧАТА.",sending:"ИЗПРАЩАНЕ..."},
 misc:{close:"ЗАТВОРИ",suggestionTitle:"ПРЕДЛОЖЕНИЯ",suggestionText:"Сподели идея за подобряване на EIXO. Предложенията могат да помогнат за бъдещи актуализации.",suggestionSubject:"ЗАГЛАВИЕ НА ПРЕДЛОЖЕНИЕТО",suggestionMessage:"ОПИШИ ПРЕДЛОЖЕНИЕТО СИ",suggestionSend:"ИЗПРАТИ ПРЕДЛОЖЕНИЕ",abandonTitle:"НАПУСНИ СТАЯТА",abandonQuestion:"Сигурен ли си, че искаш да напуснеш тази стая?",abandonWarning:"Ще бъдеш премахнат от стаята. За да влезеш отново, ще ти трябва кодът.",no:"НЕ",yes:"ДА",prev:"ПРЕДИШНА",next:"СЛЕДВАЩА",leave:"НАПУСНИ СТАЯТА",abandon:"ИЗОСТАВИ СТАЯТА"},
 account:{title:"НАСТРОЙКИ НА АКАУНТА",name:"ИМЕ",avatar:"АВАТАР",border:"РАМКА НА АВАТАРА",save:"ЗАПАЗИ",close:"ЗАТВОРИ",saved:"НАСТРОЙКИТЕ СА ЗАПАЗЕНИ.",admin:"АДМИНИСТРАЦИЯ",playerName:"ИГРАЧ (ИМЕ)",vip:"VIP 0–6",role:"РОЛЯ",moderator:"МОДЕРАТОР",player:"ИГРАЧ",setVip:"ЗАДАЙ VIP",setRole:"ЗАДАЙ РОЛЯ",kick:"ИЗГОНИ",ban24:"БАН 24Ч",banPermanent:"ПОСТОЯНЕН БАН",moderation:"МОДЕРАЦИЯ",done:"ДЕЙСТВИЕТО Е ЗАВЪРШЕНО."},
 vip:{close:"ЗАТВОРИ",statusNone:"Все още нямаш VIP.",statusLevel:"Имаш VIP #{n}. VIP е постоянен.",statusInf:"Имаш VIP ∞. Подкрепата може да продължи без лимит.",benefitsTitle:"VIP ПРЕДИМСТВА",benefits:["Показвано име с интервали и специални знаци","Отделни цветове и анимации за всеки знак","10 ексклузивни VIP цвята","По-големи частни стаи според нивото","VIP етикетът остава постоянно в акаунта"],buy:"КУПИ VIP {n} (ТЕСТ)",buyInf:"КУПИ VIP ∞ (ТЕСТ)",activateError:"VIP не можа да бъде активиран.",customizeTitle:"ПЕРСОНАЛИЗИРАЙ VIP ИМЕ",customizeDesc:"Показваното име може да използва интервали, символи и специални знаци. Всеки знак може да има собствен цвят и анимация.",visualName:"VIP ПОКАЗВАНО ИМЕ",letter:"ЗНАК",color:"ЦВЯТ",effect:"ЕФЕКТ",worldTag:"ЦВЯТ НА СВЕТОВНИЯ ЕТИКЕТ",countryTag:"ЦВЯТ НА НАЦИОНАЛНИЯ ЕТИКЕТ",save:"ЗАПАЗИ",lockOn:"VIP ∞ — избери различен цвят за всеки етикет.",lockOff:"САМО VIP ∞ — достигни последното ниво, за да персонализираш етикетите.",player:"ИГРАЧ",saveError:"Не можа да се запази."}
}),

hr:make({
 core:{play:"IGRAJ",ranking:"RANG-LISTA",rooms:"SOBE",about:"O IGRI",myRooms:"MOJE SOBE",instruction:"KLIKNI KADA JE TOČKA U SREDINI",worldTop:"SVJETSKA RANG-LISTA",fullRanking:"PRIKAŽI CIJELU RANG-LISTU",aboutText:" — jednostavna igra refleksa. Pogodi sredinu, osvoji bodove i napreduj na rang-listi.",welcome:"DOBRO DOŠAO U EIXO",countryIntro:"Najprije odaberi svoju državu.",country:"DRŽAVA",continue:"NASTAVI",nameTitle:"ODABERI IME",nameText:"Ovo ime bit će povezano s tvojim igračem i nitko drugi ga neće moći koristiti.",nameLabel:"IME IGRAČA",create:"IZRADI IGRAČA",nameInvalid:"Koristi 3–8 slova ili brojeva bez razmaka i simbola.",nameTaken:"Ovo ime je već zauzeto."},
 form:{close:"ZATVORI",nameRules:"3–8 ZNAKOVA · SLOVA I BROJEVI · BEZ RAZMAKA I SIMBOLA",contactTitle:"KONTAKT",contactText:"Oglašavanje, partnerstva, informacije ili druga pitanja.",name:"IME",subject:"PREDMET",message:"PORUKA",send:"POŠALJI ▶",bugsTitle:"PRIJAVI GREŠKU",bugsText:"Pošalji detalje kako bismo mogli ponoviti i ispraviti problem.",bugSubject:"NASLOV GREŠKE",bugMessage:"OPIŠI GREŠKU, ŠTO SI NAPRAVIO I ŠTO SE DOGODILO",sendBug:"POŠALJI GREŠKU ▶",customizeTitle:"PRILAGODI IME",customizeHint:"Dostupne opcije ovise o tvojoj poziciji na rang-listi.",visualName:"PRIKAZNO IME",nameColor:"BOJA IMENA",effect:"EFEKT",save:"SPREMI ▶",worldTab:"🌐 SVIJET",loading:"UČITAVANJE...",emptyRanking:"JOŠ NEMA IGRAČA",emptyFull:"JOŠ NEMA IGRAČA",players:"IGRAČI",leaveRoom:"NAPUSTI SOBU",enterRoom:"UĐI U SOBU",room:"SOBA",messageSent:"Poruka je poslana. Hvala!"},
 menu:{settings:"POSTAVKE",customize:"PRILAGODI IME",bugs:"PRIJAVI GREŠKU",suggestions:"PRIJEDLOZI",contact:"KONTAKT",logout:"ODJAVA",vipSoon:"VIP — USKORO",vipCustomize:"PRILAGODI VIP IME",signIn:"PRIJAVA"},
 rooms:{createRoom:"IZRADI SOBU",createRoomTitle:"IZRADI SOBU",roomName:"NAZIV SOBE",players:"IGRAČI",create:"IZRADI",roomCreated:"SOBA JE IZRAĐENA",shareCode:"Podijeli ovaj kod s prijateljima da se mogu pridružiti.",copyCode:"KOPIRAJ KOD",copied:"KOD JE KOPIRAN",myRoomsTitle:"MOJE SOBE",addRoom:"DODAJ SOBU",roomCode:"KOD SOBE",join:"PRIDRUŽI SE",loading:"UČITAVANJE...",empty:"JOŠ NISI NI U JEDNOJ SOBI.",full:"PUNA",playersLabel:"IGRAČI",invalidName:"Nevažeći naziv sobe.",invalidCode:"Nevažeći kod.",notFound:"Soba nije pronađena.",fullError:"Ova soba je puna.",createdError:"Sobu nije bilo moguće izraditi."},
 chat:{title:"CHAT",global:"GLOBALNO",all:"SVI IGRAČI",only:"SAMO",write:"NAPIŠI PORUKU...",writeN:"NAPIŠI ZA SVOJU DRŽAVU...",hint:"MAKS. 300 ZNAKOVA · BEZ SPAMA",empty:"JOŠ NEMA PORUKA.<br>BUDI PRVI.",need:"IZRADI IGRAČA ZA KORIŠTENJE CHATA.",sending:"SLANJE..."},
 misc:{close:"ZATVORI",suggestionTitle:"PRIJEDLOZI",suggestionText:"Podijeli ideju za poboljšanje EIXO-a. Prijedlozi mogu pomoći oblikovati buduća ažuriranja.",suggestionSubject:"NASLOV PRIJEDLOGA",suggestionMessage:"OPIŠI SVOJ PRIJEDLOG",suggestionSend:"POŠALJI PRIJEDLOG",abandonTitle:"NAPUSTI SOBU",abandonQuestion:"Jesi li siguran da želiš napustiti ovu sobu?",abandonWarning:"Bit ćeš uklonjen iz sobe. Za ponovni ulazak trebat će ti kod sobe.",no:"NE",yes:"DA",prev:"PRETHODNA",next:"SLJEDEĆA",leave:"NAPUSTI SOBU",abandon:"ODUSTANI OD SOBE"},
 account:{title:"POSTAVKE RAČUNA",name:"IME",avatar:"AVATAR",border:"OKVIR AVATARA",save:"SPREMI",close:"ZATVORI",saved:"POSTAVKE SU SPREMLJENE.",admin:"ADMINISTRACIJA",playerName:"IGRAČ (IME)",vip:"VIP 0–6",role:"ULOGA",moderator:"MODERATOR",player:"IGRAČ",setVip:"POSTAVI VIP",setRole:"POSTAVI ULOGU",kick:"IZBACI",ban24:"ZABRANI 24H",banPermanent:"TRAJNA ZABRANA",moderation:"MODERACIJA",done:"RADNJA JE DOVRŠENA."},
 vip:{close:"ZATVORI",statusNone:"Još nemaš VIP.",statusLevel:"Imaš VIP #{n}. VIP je trajan.",statusInf:"Imaš VIP ∞. Podrška se može nastaviti bez ograničenja.",benefitsTitle:"VIP POGODNOSTI",benefits:["Prikazno ime s razmacima i posebnim znakovima","Neovisne boje i animacije za svaki znak","10 ekskluzivnih VIP boja","Veće privatne sobe ovisno o razini","VIP oznaka trajno ostaje na računu"],buy:"KUPI VIP {n} (TEST)",buyInf:"KUPI VIP ∞ (TEST)",activateError:"VIP nije moguće aktivirati.",customizeTitle:"PRILAGODI VIP IME",customizeDesc:"Prikazno ime može sadržavati razmake, simbole i posebne znakove. Svaki znak može imati vlastitu boju i animaciju.",visualName:"VIP PRIKAZNO IME",letter:"ZNAK",color:"BOJA",effect:"EFEKT",worldTag:"BOJA SVJETSKE OZNAKE",countryTag:"BOJA NACIONALNE OZNAKE",save:"SPREMI",lockOn:"VIP ∞ — odaberi drugu boju za svaku oznaku.",lockOff:"SAMO VIP ∞ — dosegnite zadnju razinu za prilagodbu oznaka.",player:"IGRAČ",saveError:"Nije moguće spremiti."}
}),

sr:make({
 core:{play:"ИГРАЈ",ranking:"РАНГ-ЛИСТА",rooms:"СОБЕ",about:"О ИГРИ",myRooms:"МОЈЕ СОБЕ",instruction:"КЛИКНИ КАДА ЈЕ ТАЧКА У СРЕДИНИ",worldTop:"СВЕТСКА РАНГ-ЛИСТА",fullRanking:"ПРИКАЖИ ЦЕЛУ РАНГ-ЛИСТУ",aboutText:" — једноставна игра рефлекса. Погоди средину, освајај поене и напредуј на ранг-листи.",welcome:"ДОБРО ДОШАО У EIXO",countryIntro:"Прво изабери своју земљу.",country:"ЗЕМЉА",continue:"НАСТАВИ",nameTitle:"ИЗАБЕРИ ИМЕ",nameText:"Ово име ће бити повезано са твојим играчем и нико други неће моћи да га користи.",nameLabel:"ИМЕ ИГРАЧА",create:"НАПРАВИ ИГРАЧА",nameInvalid:"Користи 3–8 слова или бројева без размака и симбола.",nameTaken:"Ово име је већ заузето."},
 form:{close:"ЗАТВОРИ",nameRules:"3–8 ЗНАКОВА · СЛОВА И БРОЈЕВИ · БЕЗ РАЗМАКА И СИМБОЛА",contactTitle:"КОНТАКТ",contactText:"Оглашавање, партнерства, информације или друга питања.",name:"ИМЕ",subject:"НАСЛОВ",message:"ПОРУКА",send:"ПОШАЉИ ▶",bugsTitle:"ПРИЈАВИ ГРЕШКУ",bugsText:"Пошаљи детаље како бисмо могли да поновимо и исправимо проблем.",bugSubject:"НАСЛОВ ГРЕШКЕ",bugMessage:"ОПИШИ ГРЕШКУ, ШТА СИ УРАДИО И ШТА СЕ ДЕСИЛО",sendBug:"ПОШАЉИ ГРЕШКУ ▶",customizeTitle:"ПРИЛАГОДИ ИМЕ",customizeHint:"Доступне опције зависе од твоје позиције на ранг-листи.",visualName:"ПРИКАЗНО ИМЕ",nameColor:"БОЈА ИМЕНА",effect:"ЕФЕКАТ",save:"САЧУВАЈ ▶",worldTab:"🌐 СВЕТ",loading:"УЧИТАВАЊЕ...",emptyRanking:"ЈОШ НЕМА ИГРАЧА",emptyFull:"ЈОШ НЕМА ИГРАЧА",players:"ИГРАЧИ",leaveRoom:"НАПУСТИ СОБУ",enterRoom:"УЂИ У СОБУ",room:"СОБА",messageSent:"Порука је послата. Хвала!"},
 menu:{settings:"ПОДЕШАВАЊА",customize:"ПРИЛАГОДИ ИМЕ",bugs:"ПРИЈАВИ ГРЕШКУ",suggestions:"ПРЕДЛОЗИ",contact:"КОНТАКТ",logout:"ОДЈАВА",vipSoon:"VIP — УСКОРО",vipCustomize:"ПРИЛАГОДИ VIP ИМЕ",signIn:"ПРИЈАВА"},
 rooms:{createRoom:"НАПРАВИ СОБУ",createRoomTitle:"НАПРАВИ СОБУ",roomName:"НАЗИВ СОБЕ",players:"ИГРАЧИ",create:"НАПРАВИ",roomCreated:"СОБА ЈЕ НАПРАВЉЕНА",shareCode:"Подели овај код са пријатељима да могу да се придруже.",copyCode:"КОПИРАЈ КОД",copied:"КОД ЈЕ КОПИРАН",myRoomsTitle:"МОЈЕ СОБЕ",addRoom:"ДОДАЈ СОБУ",roomCode:"КОД СОБЕ",join:"ПРИДРУЖИ СЕ",loading:"УЧИТАВАЊЕ...",empty:"ЈОШ НИСИ НИ У ЈЕДНОЈ СОБИ.",full:"ПУНА",playersLabel:"ИГРАЧИ",invalidName:"Неважећи назив собе.",invalidCode:"Неважећи код.",notFound:"Соба није пронађена.",fullError:"Ова соба је пуна.",createdError:"Није могуће направити собу."},
 chat:{title:"ЧАТ",global:"ГЛОБАЛНО",all:"СВИ ИГРАЧИ",only:"САМО",write:"НАПИШИ ПОРУКУ...",writeN:"ПИШИ ЗА СВОЈУ ЗЕМЉУ...",hint:"МАКС. 300 ЗНАКОВА · БЕЗ СПАМА",empty:"ЈОШ НЕМА ПОРУКА.<br>БУДИ ПРВИ.",need:"НАПРАВИ ИГРАЧА ДА БИ КОРИСТИО ЧАТ.",sending:"СЛАЊЕ..."},
 misc:{close:"ЗАТВОРИ",suggestionTitle:"ПРЕДЛОЗИ",suggestionText:"Подели идеју за побољшање EIXO-а. Предлози могу помоћи у обликовању будућих ажурирања.",suggestionSubject:"НАСЛОВ ПРЕДЛОГА",suggestionMessage:"ОПИШИ СВОЈ ПРЕДЛОГ",suggestionSend:"ПОШАЉИ ПРЕДЛОГ",abandonTitle:"НАПУСТИ СОБУ",abandonQuestion:"Да ли сигурно желиш да напустиш ову собу?",abandonWarning:"Бићеш уклоњен из собе. За поновни улазак требаће ти код собе.",no:"НЕ",yes:"ДА",prev:"ПРЕТХОДНА",next:"СЛЕДЕЋА",leave:"НАПУСТИ СОБУ",abandon:"НАПУСТИ СОБУ"},
 account:{title:"ПОДЕШАВАЊА НАЛОГА",name:"ИМЕ",avatar:"АВАТАР",border:"ОКВИР АВАТАРА",save:"САЧУВАЈ",close:"ЗАТВОРИ",saved:"ПОДЕШАВАЊА СУ САЧУВАНА.",admin:"АДМИНИСТРАЦИЈА",playerName:"ИГРАЧ (ИМЕ)",vip:"VIP 0–6",role:"УЛОГА",moderator:"МОДЕРАТОР",player:"ИГРАЧ",setVip:"ПОСТАВИ VIP",setRole:"ПОСТАВИ УЛОГУ",kick:"ИЗБАЦИ",ban24:"ЗАБРАНА 24Ч",banPermanent:"ТРАЈНА ЗАБРАНА",moderation:"МОДЕРАЦИЈА",done:"РАДЊА ЈЕ ЗАВРШЕНА."},
 vip:{close:"ЗАТВОРИ",statusNone:"Још немаш VIP.",statusLevel:"Имаш VIP #{n}. VIP је трајан.",statusInf:"Имаш VIP ∞. Подршка може да се настави без ограничења.",benefitsTitle:"VIP ПОГОДНОСТИ",benefits:["Приказно име са размацима и посебним знаковима","Посебне боје и анимације за сваки знак","10 ексклузивних VIP боја","Веће приватне собе у зависности од нивоа","VIP ознака трајно остаје на налогу"],buy:"КУПИ VIP {n} (ТЕСТ)",buyInf:"КУПИ VIP ∞ (ТЕСТ)",activateError:"VIP није могуће активирати.",customizeTitle:"ПРИЛАГОДИ VIP ИМЕ",customizeDesc:"Приказно име може да садржи размаке, симболе и посебне знакове. Сваки знак може имати своју боју и анимацију.",visualName:"VIP ПРИКАЗНО ИМЕ",letter:"ЗНАК",color:"БОЈА",effect:"ЕФЕКАТ",worldTag:"БОЈА СВЕТСКЕ ОЗНАКЕ",countryTag:"БОЈА НАЦИОНАЛНЕ ОЗНАКЕ",save:"САЧУВАЈ",lockOn:"VIP ∞ — изабери другу боју за сваку ознаку.",lockOff:"САМО VIP ∞ — достигни последњи ниво за прилагођавање ознака.",player:"ИГРАЧ",saveError:"Није могуће сачувати."}
}),

sl:make({
 core:{play:"IGRAJ",ranking:"LESTVICA",rooms:"SOBE",about:"O IGRI",myRooms:"MOJE SOBE",instruction:"KLIKNI, KO JE TOČKA NA SREDINI",worldTop:"SVETOVNA LESTVICA",fullRanking:"PRIKAŽI CELOTNO LESTVICO",aboutText:" — preprosta igra refleksov. Zadeni sredino, zbiraj točke in se vzpenjaj po lestvici.",welcome:"DOBRODOŠEL V EIXO",countryIntro:"Najprej izberi svojo državo.",country:"DRŽAVA",continue:"NADALJUJ",nameTitle:"IZBERI IME",nameText:"To ime bo povezano s tvojim igralcem in ga ne bo mogel uporabljati nihče drug.",nameLabel:"IME IGRALCA",create:"USTVARI IGRALCA",nameInvalid:"Uporabi 3–8 črk ali številk brez presledkov in simbolov.",nameTaken:"To ime je že zasedeno."},
 form:{close:"ZAPRI",nameRules:"3–8 ZNAKOV · ČRKE IN ŠTEVILKE · BREZ PRESLEDKOV ALI SIMBOLOV",contactTitle:"KONTAKT",contactText:"Oglaševanje, partnerstva, informacije ali druga vprašanja.",name:"IME",subject:"ZADEVA",message:"SPOROČILO",send:"POŠLJI ▶",bugsTitle:"PRIJAVI NAPAKO",bugsText:"Pošlji podrobnosti, da lahko težavo ponovimo in odpravimo.",bugSubject:"NASLOV NAPAKE",bugMessage:"OPIŠI NAPAKO, KAJ SI NAREDIL IN KAJ SE JE ZGODILO",sendBug:"POŠLJI NAPAKO ▶",customizeTitle:"PRILAGODI IME",customizeHint:"Razpoložljive možnosti so odvisne od tvojega mesta na lestvici.",visualName:"PRIKAZNO IME",nameColor:"BARVA IMENA",effect:"UČINEK",save:"SHRANI ▶",worldTab:"🌐 SVET",loading:"NALAGANJE...",emptyRanking:"IGRALCEV ŠE NI",emptyFull:"IGRALCEV ŠE NI",players:"IGRALCI",leaveRoom:"ZAPUSTI SOBO",enterRoom:"VSTOPI V SOBO",room:"SOBA",messageSent:"Sporočilo je poslano. Hvala!"},
 menu:{settings:"NASTAVITVE",customize:"PRILAGODI IME",bugs:"PRIJAVI NAPAKO",suggestions:"PREDLOGI",contact:"KONTAKT",logout:"ODJAVA",vipSoon:"VIP — Kmalu",vipCustomize:"PRILAGODI VIP IME",signIn:"PRIJAVA"},
 rooms:{createRoom:"USTVARI SOBO",createRoomTitle:"USTVARI SOBO",roomName:"IME SOBE",players:"IGRALCI",create:"USTVARI",roomCreated:"SOBA USTVARJENA",shareCode:"Deli to kodo s prijatelji, da se lahko pridružijo.",copyCode:"KOPIRAJ KODO",copied:"KODA KOPIRANA",myRoomsTitle:"MOJE SOBE",addRoom:"DODAJ SOBO",roomCode:"KODA SOBE",join:"PRIDRUŽI SE",loading:"NALAGANJE...",empty:"ŠE NISI V NOBENI SOBI.",full:"POLNA",playersLabel:"IGRALCI",invalidName:"Neveljavno ime sobe.",invalidCode:"Neveljavna koda.",notFound:"Soba ni najdena.",fullError:"Ta soba je polna.",createdError:"Sobe ni bilo mogoče ustvariti."},
 chat:{title:"KLEPET",global:"GLOBALNO",all:"VSI IGRALCI",only:"SAMO",write:"NAPIŠI SPOROČILO...",writeN:"PIŠI ZA SVOJO DRŽAVO...",hint:"NAJVEČ 300 ZNAKOV · BREZ SPAMA",empty:"SPOROČIL ŠE NI.<br>BODI PRVI.",need:"USTVARI IGRALCA ZA UPORABO KLEPETA.",sending:"POŠILJANJE..."},
 misc:{close:"ZAPRI",suggestionTitle:"PREDLOGI",suggestionText:"Deli idejo za izboljšanje EIXO. Predlogi lahko pomagajo oblikovati prihodnje posodobitve.",suggestionSubject:"NASLOV PREDLOGA",suggestionMessage:"OPIŠI SVOJ PREDLOG",suggestionSend:"POŠLJI PREDLOG",abandonTitle:"ZAPUSTI SOBO",abandonQuestion:"Ali res želiš zapustiti to sobo?",abandonWarning:"Odstranjen boš iz sobe. Za ponovni vstop boš potreboval kodo sobe.",no:"NE",yes:"DA",prev:"PREJŠNJA",next:"NASLEDNJA",leave:"ZAPUSTI SOBO",abandon:"ZAPUSTI SOBO"},
 account:{title:"NASTAVITVE RAČUNA",name:"IME",avatar:"AVATAR",border:"OKVIR AVATARJA",save:"SHRANI",close:"ZAPRI",saved:"NASTAVITVE SHRANJENE.",admin:"ADMINISTRACIJA",playerName:"IGRALEC (IME)",vip:"VIP 0–6",role:"VLOGA",moderator:"MODERATOR",player:"IGRALEC",setVip:"NASTAVI VIP",setRole:"NASTAVI VLOGO",kick:"ODSTRANI",ban24:"PREPOVED 24H",banPermanent:"TRAJNA PREPOVED",moderation:"MODERACIJA",done:"DEJANJE KONČANO."},
 vip:{close:"ZAPRI",statusNone:"VIP-a še nimaš.",statusLevel:"Imaš VIP #{n}. VIP je trajen.",statusInf:"Imaš VIP ∞. Podpora se lahko nadaljuje brez omejitev.",benefitsTitle:"VIP UGODNOSTI",benefits:["Prikazno ime s presledki in posebnimi znaki","Ločene barve in animacije za vsak znak","10 ekskluzivnih VIP barv","Večje zasebne sobe glede na raven","VIP oznaka trajno ostane na računu"],buy:"KUPI VIP {n} (TEST)",buyInf:"KUPI VIP ∞ (TEST)",activateError:"VIP-a ni bilo mogoče aktivirati.",customizeTitle:"PRILAGODI VIP IME",customizeDesc:"Prikazno ime lahko vsebuje presledke, simbole in posebne znake. Vsak znak ima lahko svojo barvo in animacijo.",visualName:"VIP PRIKAZNO IME",letter:"ZNAK",color:"BARVA",effect:"UČINEK",worldTag:"BARVA SVETOVNE OZNAKE",countryTag:"BARVA DRŽAVNE OZNAKE",save:"SHRANI",lockOn:"VIP ∞ — izberi drugo barvo za vsako oznako.",lockOff:"SAMO VIP ∞ — dosezi zadnjo raven za prilagajanje oznak.",player:"IGRALEC",saveError:"Ni bilo mogoče shraniti."}
}),

is:make({
 core:{play:"SPILA",ranking:"STIGATAFLA",rooms:"HERBERGI",about:"UM",myRooms:"HERBERGIN MÍN",instruction:"SMELLTU ÞEGAR PUNKTURINN ER Í MIÐJUNNI",worldTop:"HEIMSSTIGATAFLA",fullRanking:"SJÁ ALLA STIGATÖFLUNA",aboutText:" — einfaldur viðbragðsleikur. Hittu miðjuna, safnaðu stigum og klifraðu upp stigatöfluna.",welcome:"VELKOMIN Í EIXO",countryIntro:"Veldu fyrst landið þitt.",country:"LAND",continue:"HALDA ÁFRAM",nameTitle:"VELDU NAFN",nameText:"Þetta nafn verður tengt leikmanninum þínum og enginn annar getur notað það.",nameLabel:"NAFN LEIKMANNS",create:"STOFNA LEIKMANN",nameInvalid:"Notaðu 3–8 stafi eða tölur, án bila eða tákna.",nameTaken:"Þetta nafn er þegar í notkun."},
 form:{close:"LOKA",nameRules:"3–8 STAFIR · BÓKSTAFIR OG TÖLUR · ENGIN BIL EÐA TÁKN",contactTitle:"HAFA SAMBAND",contactText:"Auglýsingar, samstarf, upplýsingar eða aðrar spurningar.",name:"NAFN",subject:"EFNI",message:"SKILABOÐ",send:"SENDA ▶",bugsTitle:"TILKYNNA VILLU",bugsText:"Sendu upplýsingar svo við getum endurtekið og lagað vandamálið.",bugSubject:"HEITI VILLU",bugMessage:"LÝSTU VILLUNNI, HVAÐ ÞÚ GERÐIR OG HVAÐ GERÐIST",sendBug:"SENDA VILLU ▶",customizeTitle:"SÉRSNÍÐA NAFN",customizeHint:"Tiltækir valkostir ráðast af sæti þínu á stigatöflunni.",visualName:"BIRT NAFN",nameColor:"LITUR NAFNS",effect:"ÁHRIF",save:"VISTA ▶",worldTab:"🌐 HEIMUR",loading:"HLEÐ...",emptyRanking:"ENGIR LEIKMENN ENN",emptyFull:"ENGIR LEIKMENN ENN",players:"LEIKMENN",leaveRoom:"YFIRGEFA HERBERGI",enterRoom:"FARA Í HERBERGI",room:"HERBERGI",messageSent:"Skilaboð send. Takk!"},
 menu:{settings:"STILLINGAR",customize:"SÉRSNÍÐA NAFN",bugs:"TILKYNNA VILLU",suggestions:"TILLÖGUR",contact:"HAFA SAMBAND",logout:"SKRÁ ÚT",vipSoon:"VIP — VÆNTANLEGT",vipCustomize:"SÉRSNÍÐA VIP-NAFN",signIn:"SKRÁ INN"},
 rooms:{createRoom:"STOFNA HERBERGI",createRoomTitle:"STOFNA HERBERGI",roomName:"NAFN HERBERGIS",players:"LEIKMENN",create:"STOFNA",roomCreated:"HERBERGI STOFNAÐ",shareCode:"Deildu þessum kóða með vinum svo þeir geti tekið þátt.",copyCode:"AFRITA KÓÐA",copied:"KÓÐI AFRITAÐUR",myRoomsTitle:"HERBERGIN MÍN",addRoom:"BÆTA VIÐ HERBERGI",roomCode:"HERBERGISKÓÐI",join:"TAKA ÞÁTT",loading:"HLEÐ...",empty:"ÞÚ ERT EKKI Í NEINU HERBERGI ENN.",full:"FULLT",playersLabel:"LEIKMENN",invalidName:"Ógilt nafn herbergis.",invalidCode:"Ógildur kóði.",notFound:"Herbergi fannst ekki.",fullError:"Herbergið er fullt.",createdError:"Ekki tókst að stofna herbergi."},
 chat:{title:"SPJALL",global:"ALÞJÓÐLEGT",all:"ALLIR LEIKMENN",only:"AÐEINS",write:"SKRIFA SKILABOÐ...",writeN:"SKRIFA FYRIR LANDIÐ ÞITT...",hint:"HÁM. 300 STAFIR · EKKERT RUSL",empty:"ENGIN SKILABOÐ ENN.<br>VERTU FYRSTUR.",need:"STOFNAÐU LEIKMANN TIL AÐ NOTA SPJALLIÐ.",sending:"SENDI..."},
 misc:{close:"LOKA",suggestionTitle:"TILLÖGUR",suggestionText:"Deildu hugmynd til að bæta EIXO. Tillögur geta hjálpað til við framtíðaruppfærslur.",suggestionSubject:"HEITI TILLÖGU",suggestionMessage:"LÝSTU TILLÖGUNNI ÞINNI",suggestionSend:"SENDA TILLÖGU",abandonTitle:"YFIRGEFA HERBERGI",abandonQuestion:"Ertu viss um að þú viljir yfirgefa þetta herbergi?",abandonWarning:"Þú verður fjarlægður úr herberginu. Til að taka þátt aftur þarftu herbergiskóðann.",no:"NEI",yes:"JÁ",prev:"FYRRI",next:"NÆSTA",leave:"YFIRGEFA HERBERGI",abandon:"YFIRGEFA HERBERGI"},
 account:{title:"REIKNINGSSTILLINGAR",name:"NAFN",avatar:"AVATAR",border:"RAMMI AVATARS",save:"VISTA",close:"LOKA",saved:"STILLINGAR VISTAÐAR.",admin:"STJÓRNUN",playerName:"LEIKMAÐUR (NAFN)",vip:"VIP 0–6",role:"HLUTVERK",moderator:"UMSJÓNARMAÐUR",player:"LEIKMAÐUR",setVip:"STILLA VIP",setRole:"STILLA HLUTVERK",kick:"REKA ÚT",ban24:"BANNA 24 KLST.",banPermanent:"VARANLEGT BANN",moderation:"UMSJÓN",done:"AÐGERÐ LOKIÐ."},
 vip:{close:"LOKA",statusNone:"Þú ert ekki með VIP enn.",statusLevel:"Þú ert með VIP #{n}. VIP er varanlegt.",statusInf:"Þú ert með VIP ∞. Stuðningur getur haldið áfram án takmarkana.",benefitsTitle:"VIP-FRÍÐINDI",benefits:["Birt nafn með bilum og sérstöfum","Sjálfstæðir litir og hreyfingar fyrir hvern staf","10 sérstakir VIP-litir","Stærri einkaherbergi eftir stigi","VIP-merkið helst varanlega á reikningnum"],buy:"KAUPA VIP {n} (PRÓF)",buyInf:"KAUPA VIP ∞ (PRÓF)",activateError:"Ekki tókst að virkja VIP.",customizeTitle:"SÉRSNÍÐA VIP-NAFN",customizeDesc:"Birta nafnið má innihalda bil, tákn og sérstafi. Hver stafur getur haft sinn lit og hreyfingu.",visualName:"VIP-BIRT NAFN",letter:"STAFUR",color:"LITUR",effect:"ÁHRIF",worldTag:"LITUR HEIMSMERKIS",countryTag:"LITUR LANDSMERKIS",save:"VISTA",lockOn:"VIP ∞ — veldu annan lit fyrir hvert merki.",lockOff:"AÐEINS VIP ∞ — náðu síðasta stigi til að sérsníða merkin.",player:"LEIKMAÐUR",saveError:"Ekki tókst að vista."}
})

  };
  window.EixoExtraLocales=L;
  try{
    Object.entries(L).forEach(([code,data])=>{if(typeof translations!=='undefined')translations[code]=data.core;});
  }catch(_){}
})();