/* EIXO: translations for secondary UI not covered by the legacy dictionaries. */
(function(){
 const EN={close:'CLOSE',suggestionTitle:'SUGGESTIONS',suggestionText:'Share an idea to improve EIXO. Suggestions can help shape future updates.',suggestionSubject:'SUGGESTION TITLE',suggestionMessage:'DESCRIBE YOUR SUGGESTION',suggestionSend:'SEND SUGGESTION',abandonTitle:'ABANDON ROOM',abandonQuestion:'Are you sure you want to abandon this room?',abandonWarning:'You will be removed from this room. To join again, you will need the room code.',no:'NO',yes:'YES',prev:'PREVIOUS',next:'NEXT',leave:'LEAVE ROOM',abandon:'ABANDON ROOM'};
 const T={
  pt:{close:'FECHAR',suggestionTitle:'SUGESTÕES',suggestionText:'Partilha uma ideia para melhorar o EIXO. As sugestões podem ajudar a definir futuras atualizações.',suggestionSubject:'TÍTULO DA SUGESTÃO',suggestionMessage:'DESCREVE A TUA SUGESTÃO',suggestionSend:'ENVIAR SUGESTÃO',abandonTitle:'ABANDONAR SALA',abandonQuestion:'Tens a certeza que queres abandonar a sala?',abandonWarning:'Vais ser removido desta sala. Para voltares a entrar, precisas novamente do código da sala.',no:'NÃO',yes:'SIM',prev:'ANTERIOR',next:'SEGUINTE',leave:'SAIR DA SALA',abandon:'ABANDONAR SALA'},
  es:{close:'CERRAR',suggestionTitle:'SUGERENCIAS',suggestionText:'Comparte una idea para mejorar EIXO. Las sugerencias pueden ayudar a definir futuras actualizaciones.',suggestionSubject:'TÍTULO DE LA SUGERENCIA',suggestionMessage:'DESCRIBE TU SUGERENCIA',suggestionSend:'ENVIAR SUGERENCIA',abandonTitle:'ABANDONAR SALA',abandonQuestion:'¿Seguro que quieres abandonar esta sala?',abandonWarning:'Serás eliminado de esta sala. Para volver a entrar necesitarás el código de la sala.',no:'NO',yes:'SÍ',prev:'ANTERIOR',next:'SIGUIENTE',leave:'SALIR DE LA SALA',abandon:'ABANDONAR SALA'},
  fr:{close:'FERMER',suggestionTitle:'SUGGESTIONS',suggestionText:'Partage une idée pour améliorer EIXO. Les suggestions peuvent aider à définir les prochaines mises à jour.',suggestionSubject:'TITRE DE LA SUGGESTION',suggestionMessage:'DÉCRIS TA SUGGESTION',suggestionSend:'ENVOYER LA SUGGESTION',abandonTitle:'QUITTER LA SALLE',abandonQuestion:'Veux-tu vraiment quitter cette salle ?',abandonWarning:'Tu seras retiré de cette salle. Pour revenir, tu auras besoin du code de la salle.',no:'NON',yes:'OUI',prev:'PRÉCÉDENT',next:'SUIVANT',leave:'QUITTER LA SALLE',abandon:'ABANDONNER LA SALLE'},
  de:{close:'SCHLIESSEN',suggestionTitle:'VORSCHLÄGE',suggestionText:'Teile eine Idee, um EIXO zu verbessern. Vorschläge können zukünftige Updates mitgestalten.',suggestionSubject:'TITEL DES VORSCHLAGS',suggestionMessage:'BESCHREIBE DEINEN VORSCHLAG',suggestionSend:'VORSCHLAG SENDEN',abandonTitle:'RAUM VERLASSEN',abandonQuestion:'Möchtest du diesen Raum wirklich verlassen?',abandonWarning:'Du wirst aus diesem Raum entfernt. Um erneut beizutreten, brauchst du den Raumcode.',no:'NEIN',yes:'JA',prev:'ZURÜCK',next:'WEITER',leave:'RAUM VERLASSEN',abandon:'RAUM AUFGEBEN'},
  it:{close:'CHIUDI',suggestionTitle:'SUGGERIMENTI',suggestionText:'Condividi un’idea per migliorare EIXO. I suggerimenti possono contribuire ai futuri aggiornamenti.',suggestionSubject:'TITOLO DEL SUGGERIMENTO',suggestionMessage:'DESCRIVI IL TUO SUGGERIMENTO',suggestionSend:'INVIA SUGGERIMENTO',abandonTitle:'ABBANDONA STANZA',abandonQuestion:'Vuoi davvero abbandonare questa stanza?',abandonWarning:'Verrai rimosso dalla stanza. Per rientrare avrai bisogno del codice.',no:'NO',yes:'SÌ',prev:'PRECEDENTE',next:'SUCCESSIVO',leave:'ESCI DALLA STANZA',abandon:'ABBANDONA STANZA'},
  ja:{close:'閉じる',suggestionTitle:'提案',suggestionText:'EIXOを改善するアイデアを共有してください。提案は今後のアップデートに役立ちます。',suggestionSubject:'提案タイトル',suggestionMessage:'提案を説明してください',suggestionSend:'提案を送信',abandonTitle:'ルームを退出',abandonQuestion:'このルームを退出しますか？',abandonWarning:'このルームから削除されます。再参加するにはルームコードが必要です。',no:'いいえ',yes:'はい',prev:'前へ',next:'次へ',leave:'ルームを退出',abandon:'ルームを放棄'},
  ko:{close:'닫기',suggestionTitle:'제안',suggestionText:'EIXO를 개선할 아이디어를 공유해 주세요. 제안은 향후 업데이트에 도움이 됩니다.',suggestionSubject:'제안 제목',suggestionMessage:'제안을 설명해 주세요',suggestionSend:'제안 보내기',abandonTitle:'방 나가기',abandonQuestion:'이 방을 나가시겠습니까?',abandonWarning:'이 방에서 제거됩니다. 다시 참여하려면 방 코드가 필요합니다.',no:'아니요',yes:'예',prev:'이전',next:'다음',leave:'방 나가기',abandon:'방 포기'},
  zh:{close:'关闭',suggestionTitle:'建议',suggestionText:'分享改进 EIXO 的想法。你的建议可能会影响未来更新。',suggestionSubject:'建议标题',suggestionMessage:'描述你的建议',suggestionSend:'发送建议',abandonTitle:'退出房间',abandonQuestion:'确定要退出这个房间吗？',abandonWarning:'你将被移出该房间。再次加入时需要房间代码。',no:'否',yes:'是',prev:'上一页',next:'下一页',leave:'退出房间',abandon:'放弃房间'},
  ru:{close:'ЗАКРЫТЬ',suggestionTitle:'ПРЕДЛОЖЕНИЯ',suggestionText:'Поделитесь идеей, как улучшить EIXO. Предложения могут повлиять на будущие обновления.',suggestionSubject:'НАЗВАНИЕ ПРЕДЛОЖЕНИЯ',suggestionMessage:'ОПИШИТЕ ПРЕДЛОЖЕНИЕ',suggestionSend:'ОТПРАВИТЬ ПРЕДЛОЖЕНИЕ',abandonTitle:'ПОКИНУТЬ КОМНАТУ',abandonQuestion:'Точно покинуть эту комнату?',abandonWarning:'Вы будете удалены из комнаты. Для повторного входа потребуется код комнаты.',no:'НЕТ',yes:'ДА',prev:'НАЗАД',next:'ДАЛЕЕ',leave:'ВЫЙТИ ИЗ КОМНАТЫ',abandon:'ПОКИНУТЬ КОМНАТУ'},
  pl:{close:'ZAMKNIJ',suggestionTitle:'SUGESTIE',suggestionText:'Podziel się pomysłem na ulepszenie EIXO. Sugestie mogą wpłynąć na przyszłe aktualizacje.',suggestionSubject:'TYTUŁ SUGESTII',suggestionMessage:'OPISZ SWOJĄ SUGESTIĘ',suggestionSend:'WYŚLIJ SUGESTIĘ',abandonTitle:'OPUŚĆ POKÓJ',abandonQuestion:'Na pewno chcesz opuścić ten pokój?',abandonWarning:'Zostaniesz usunięty z pokoju. Aby dołączyć ponownie, potrzebujesz kodu pokoju.',no:'NIE',yes:'TAK',prev:'POPRZEDNIA',next:'NASTĘPNA',leave:'OPUŚĆ POKÓJ',abandon:'PORZUĆ POKÓJ'},
  nl:{close:'SLUITEN',suggestionTitle:'SUGGESTIES',suggestionText:'Deel een idee om EIXO te verbeteren. Suggesties kunnen toekomstige updates helpen bepalen.',suggestionSubject:'TITEL VAN SUGGESTIE',suggestionMessage:'BESCHRIJF JE SUGGESTIE',suggestionSend:'SUGGESTIE VERSTUREN',abandonTitle:'KAMER VERLATEN',abandonQuestion:'Weet je zeker dat je deze kamer wilt verlaten?',abandonWarning:'Je wordt uit deze kamer verwijderd. Om opnieuw mee te doen heb je de kamercode nodig.',no:'NEE',yes:'JA',prev:'VORIGE',next:'VOLGENDE',leave:'KAMER VERLATEN',abandon:'KAMER OPGEVEN'},
  tr:{close:'KAPAT',suggestionTitle:'ÖNERİLER',suggestionText:'EIXO’yu geliştirmek için bir fikir paylaş. Öneriler gelecekteki güncellemeleri şekillendirebilir.',suggestionSubject:'ÖNERİ BAŞLIĞI',suggestionMessage:'ÖNERİNİ AÇIKLA',suggestionSend:'ÖNERİ GÖNDER',abandonTitle:'ODADAN AYRIL',abandonQuestion:'Bu odadan ayrılmak istediğine emin misin?',abandonWarning:'Bu odadan çıkarılacaksın. Tekrar katılmak için oda koduna ihtiyacın olacak.',no:'HAYIR',yes:'EVET',prev:'ÖNCEKİ',next:'SONRAKİ',leave:'ODADAN AYRIL',abandon:'ODAYI TERK ET'},
  ar:{close:'إغلاق',suggestionTitle:'اقتراحات',suggestionText:'شارك فكرة لتحسين EIXO. قد تساعد الاقتراحات في تشكيل التحديثات القادمة.',suggestionSubject:'عنوان الاقتراح',suggestionMessage:'اشرح اقتراحك',suggestionSend:'إرسال الاقتراح',abandonTitle:'مغادرة الغرفة',abandonQuestion:'هل أنت متأكد من مغادرة هذه الغرفة؟',abandonWarning:'ستتم إزالتك من الغرفة. للانضمام مجدداً ستحتاج إلى رمز الغرفة.',no:'لا',yes:'نعم',prev:'السابق',next:'التالي',leave:'مغادرة الغرفة',abandon:'ترك الغرفة'},
  sv:{close:'STÄNG',suggestionTitle:'FÖRSLAG',suggestionText:'Dela en idé för att förbättra EIXO. Förslag kan hjälpa till att forma framtida uppdateringar.',suggestionSubject:'FÖRSLAGETS TITEL',suggestionMessage:'BESKRIV DITT FÖRSLAG',suggestionSend:'SKICKA FÖRSLAG',abandonTitle:'LÄMNA RUM',abandonQuestion:'Är du säker på att du vill lämna rummet?',abandonWarning:'Du tas bort från rummet. För att gå med igen behöver du rumskoden.',no:'NEJ',yes:'JA',prev:'FÖREGÅENDE',next:'NÄSTA',leave:'LÄMNA RUM',abandon:'ÖVERGE RUM'},
  no:{close:'LUKK',suggestionTitle:'FORSLAG',suggestionText:'Del en idé for å forbedre EIXO. Forslag kan bidra til fremtidige oppdateringer.',suggestionSubject:'FORSLAGSTITTEL',suggestionMessage:'BESKRIV FORSLAGET DITT',suggestionSend:'SEND FORSLAG',abandonTitle:'FORLAT ROM',abandonQuestion:'Er du sikker på at du vil forlate rommet?',abandonWarning:'Du fjernes fra rommet. For å bli med igjen trenger du romkoden.',no:'NEI',yes:'JA',prev:'FORRIGE',next:'NESTE',leave:'FORLAT ROM',abandon:'FORLAT ROM'},
  da:{close:'LUK',suggestionTitle:'FORSLAG',suggestionText:'Del en idé til at forbedre EIXO. Forslag kan være med til at forme fremtidige opdateringer.',suggestionSubject:'FORSLAGSTITEL',suggestionMessage:'BESKRIV DIT FORSLAG',suggestionSend:'SEND FORSLAG',abandonTitle:'FORLAD RUM',abandonQuestion:'Er du sikker på, at du vil forlade rummet?',abandonWarning:'Du fjernes fra rummet. For at deltage igen skal du bruge rumkoden.',no:'NEJ',yes:'JA',prev:'FORRIGE',next:'NÆSTE',leave:'FORLAD RUM',abandon:'FORLAD RUM'},
  fi:{close:'SULJE',suggestionTitle:'EHDOTUKSET',suggestionText:'Jaa idea EIXOn parantamiseksi. Ehdotukset voivat auttaa tulevien päivitysten suunnittelussa.',suggestionSubject:'EHDOTUKSEN OTSIKKO',suggestionMessage:'KUVAILE EHDOTUKSESI',suggestionSend:'LÄHETÄ EHDOTUS',abandonTitle:'POISTU HUONEESTA',abandonQuestion:'Haluatko varmasti poistua tästä huoneesta?',abandonWarning:'Sinut poistetaan huoneesta. Liittyäksesi uudelleen tarvitset huonekoodin.',no:'EI',yes:'KYLLÄ',prev:'EDELLINEN',next:'SEURAAVA',leave:'POISTU HUONEESTA',abandon:'HYLKÄÄ HUONE'},
  el:{close:'ΚΛΕΙΣΙΜΟ',suggestionTitle:'ΠΡΟΤΑΣΕΙΣ',suggestionText:'Μοιράσου μια ιδέα για τη βελτίωση του EIXO. Οι προτάσεις μπορούν να βοηθήσουν στις μελλοντικές ενημερώσεις.',suggestionSubject:'ΤΙΤΛΟΣ ΠΡΟΤΑΣΗΣ',suggestionMessage:'ΠΕΡΙΓΡΑΨΕ ΤΗΝ ΠΡΟΤΑΣΗ ΣΟΥ',suggestionSend:'ΑΠΟΣΤΟΛΗ ΠΡΟΤΑΣΗΣ',abandonTitle:'ΕΞΟΔΟΣ ΑΠΟ ΔΩΜΑΤΙΟ',abandonQuestion:'Θέλεις σίγουρα να φύγεις από αυτό το δωμάτιο;',abandonWarning:'Θα αφαιρεθείς από το δωμάτιο. Για να μπεις ξανά θα χρειαστείς τον κωδικό.',no:'ΟΧΙ',yes:'ΝΑΙ',prev:'ΠΡΟΗΓΟΥΜΕΝΟ',next:'ΕΠΟΜΕΝΟ',leave:'ΕΞΟΔΟΣ ΑΠΟ ΤΟ ΔΩΜΑΤΙΟ',abandon:'ΕΓΚΑΤΑΛΕΙΨΗ ΔΩΜΑΤΙΟΥ'},
  cs:{close:'ZAVŘÍT',suggestionTitle:'NÁVRHY',suggestionText:'Sdílej nápad na zlepšení EIXO. Návrhy mohou ovlivnit budoucí aktualizace.',suggestionSubject:'NÁZEV NÁVRHU',suggestionMessage:'POPIS NÁVRHU',suggestionSend:'ODESLAT NÁVRH',abandonTitle:'OPUSTIT MÍSTNOST',abandonQuestion:'Opravdu chceš opustit tuto místnost?',abandonWarning:'Budeš z místnosti odebrán. Pro opětovný vstup budeš potřebovat kód místnosti.',no:'NE',yes:'ANO',prev:'PŘEDCHOZÍ',next:'DALŠÍ',leave:'OPUSTIT MÍSTNOST',abandon:'OPUSTIT MÍSTNOST'},
  id:{close:'TUTUP',suggestionTitle:'SARAN',suggestionText:'Bagikan ide untuk meningkatkan EIXO. Saran dapat membantu membentuk pembaruan berikutnya.',suggestionSubject:'JUDUL SARAN',suggestionMessage:'JELASKAN SARANMU',suggestionSend:'KIRIM SARAN',abandonTitle:'TINGGALKAN RUANGAN',abandonQuestion:'Yakin ingin meninggalkan ruangan ini?',abandonWarning:'Kamu akan dikeluarkan dari ruangan. Untuk bergabung lagi kamu memerlukan kode ruangan.',no:'TIDAK',yes:'YA',prev:'SEBELUMNYA',next:'BERIKUTNYA',leave:'TINGGALKAN RUANGAN',abandon:'TINGGALKAN RUANGAN'},
  th:{close:'ปิด',suggestionTitle:'ข้อเสนอแนะ',suggestionText:'แบ่งปันไอเดียเพื่อพัฒนา EIXO ข้อเสนอแนะอาจช่วยกำหนดอัปเดตในอนาคต',suggestionSubject:'หัวข้อข้อเสนอแนะ',suggestionMessage:'อธิบายข้อเสนอแนะของคุณ',suggestionSend:'ส่งข้อเสนอแนะ',abandonTitle:'ออกจากห้อง',abandonQuestion:'คุณแน่ใจหรือไม่ว่าต้องการออกจากห้องนี้?',abandonWarning:'คุณจะถูกนำออกจากห้อง หากต้องการเข้าร่วมอีกครั้งจะต้องใช้รหัสห้อง',no:'ไม่',yes:'ใช่',prev:'ก่อนหน้า',next:'ถัดไป',leave:'ออกจากห้อง',abandon:'ละทิ้งห้อง'},
  vi:{close:'ĐÓNG',suggestionTitle:'GỢI Ý',suggestionText:'Chia sẻ ý tưởng để cải thiện EIXO. Gợi ý có thể giúp định hình các bản cập nhật tương lai.',suggestionSubject:'TIÊU ĐỀ GỢI Ý',suggestionMessage:'MÔ TẢ GỢI Ý CỦA BẠN',suggestionSend:'GỬI GỢI Ý',abandonTitle:'RỜI PHÒNG',abandonQuestion:'Bạn có chắc muốn rời phòng này?',abandonWarning:'Bạn sẽ bị xóa khỏi phòng. Để tham gia lại, bạn cần mã phòng.',no:'KHÔNG',yes:'CÓ',prev:'TRƯỚC',next:'TIẾP',leave:'RỜI PHÒNG',abandon:'BỎ PHÒNG'},
  he:{close:'סגור',suggestionTitle:'הצעות',suggestionText:'שתפו רעיון לשיפור EIXO. הצעות יכולות להשפיע על עדכונים עתידיים.',suggestionSubject:'כותרת ההצעה',suggestionMessage:'תארו את ההצעה שלכם',suggestionSend:'שלח הצעה',abandonTitle:'עזיבת חדר',abandonQuestion:'בטוחים שברצונכם לעזוב את החדר?',abandonWarning:'תוסרו מהחדר. כדי להצטרף שוב תצטרכו את קוד החדר.',no:'לא',yes:'כן',prev:'הקודם',next:'הבא',leave:'עזוב חדר',abandon:'נטוש חדר'}
 };
 const player=()=>{try{return JSON.parse(localStorage.getItem('eixo_player')||'null')}catch(_){return null}};
 const lang=()=>String(document.documentElement.lang||'en').split('-')[0];
 const tr=()=>({...EN,...(T[lang()]||{}),...(window.EixoExtraLocales?.[lang()]?.misc||{})});
 function apply(){
  if(!player())return;
  const x=tr(),s=document.getElementById('suggestionModal');
  if(s){const h=s.querySelector('h2'),p=s.querySelector('p'),f=s.querySelector('form');if(h)h.textContent=x.suggestionTitle;if(p)p.textContent=x.suggestionText;if(f){const name=f.querySelector('[name="name"]'),email=f.querySelector('[name="email"]'),sub=f.querySelector('[name="subject"]'),msg=f.querySelector('[name="message"]'),b=f.querySelector('button[type="submit"]');if(name)name.placeholder=window.eixoT?window.eixoT('name','NAME'):'NAME';if(email)email.placeholder=window.eixoT?window.eixoT('email','EMAIL'):'EMAIL';if(sub)sub.placeholder=x.suggestionSubject;if(msg)msg.placeholder=x.suggestionMessage;if(b)b.textContent=x.suggestionSend;}}
  const a=document.getElementById('abandonRoomModal');
  if(a){const h=a.querySelector('h2'),ps=a.querySelectorAll('p');if(h)h.textContent=x.abandonTitle;if(ps[0])ps[0].textContent=x.abandonQuestion;if(ps[1])ps[1].textContent=x.abandonWarning;const n=document.getElementById('abandonRoomCancel'),y=document.getElementById('abandonRoomConfirm');if(n)n.textContent=x.no;if(y)y.textContent=x.yes;}
  const leave=document.getElementById('leaveActiveRoom'),abandon=document.getElementById('abandonActiveRoom'),prev=document.getElementById('prevPage'),next=document.getElementById('nextPage');
  if(leave)leave.textContent=x.leave;if(abandon)abandon.textContent=x.abandon;if(prev)prev.textContent=x.prev;if(next)next.textContent=x.next;
  document.querySelectorAll('.modal-close').forEach(b=>{const v=b.textContent.trim().toUpperCase();if(v==='CLOSE'||v==='FECHAR'||v==='CERRAR'||v==='FERMER'||v==='SCHLIESSEN'||v==='CHIUDI')b.textContent=x.close;});
 }
 apply();
 new MutationObserver(apply).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
 window.addEventListener('eixo-player-updated',apply);
 window.addEventListener('eixo-auth-ready',apply);
})();
