/* EIXO rankings + RUN identity bridge + resilient boot + Passport avatar. */
(()=>{
'use strict';
const worldEl=document.getElementById('worldRanking'),countryEl=document.getElementById('nationalRanking');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const flag=code=>{const c=String(code||'').toUpperCase();return /^[A-Z]{2}$/.test(c)?[...c].map(x=>String.fromCodePoint(127397+x.charCodeAt())).join(''):'🌐'};
const lang=()=>String(document.documentElement.lang||'en').split('-')[0];
const rankLabels={pt:'O TEU RANK É:',en:'YOUR RANK IS:',es:'TU RANGO ES:',fr:'TON RANG EST:',de:'DEIN RANG IST:',it:'IL TUO RANK È:',ja:'あなたの順位:',ko:'내 순위:',zh:'你的排名:',ru:'ТВОЙ РАНГ:',pl:'TWÓJ RANKING:',nl:'JOUW RANG IS:',tr:'SIRAN:',ar:'ترتيبك:',sv:'DIN RANK ÄR:',no:'DIN RANG ER:',da:'DIN RANG ER:',fi:'SIJOITUKSESI:',el:'Η ΚΑΤΑΤΑΞΗ ΣΟΥ:',cs:'TVÉ POŘADÍ:',id:'PERINGKATMU:',th:'อันดับของคุณ:',vi:'HẠNG CỦA BẠN:',he:'הדירוג שלך:'};
const rankLabel=()=>rankLabels[lang()]||rankLabels.en;
const safeEffect=v=>/^[a-z]+$/.test(String(v||''))?String(v):'none';
const medal=(type,n,country)=>{const label=type==='country'?esc(country)+' #'+n:'GLOBAL #'+n;return '<span class="rank-tag medal-rank '+type+'-'+n+'" title="'+label+'" aria-label="'+label+'"><span class="rank-medal-icon" aria-hidden="true"><span class="rank-medal-number">'+n+'</span></span></span>'};
const vip=n=>Number(n)>0?'<span class="vip-rank-tag vip-medal vip-rank-'+Math.min(Number(n),6)+'" title="VIP '+(Number(n)>=6?'∞':Number(n))+'"><span class="vip-medal-mark" aria-hidden="true">'+['','◆','✧','✦','♛','★','∞'][Math.min(Number(n),6)]+'</span></span>':'';
const achievement=b=>({['first-100']:'100',['skybound']:'↟',['explorer']:'✦',['pulse-10']:'◎'}[b]||'');
const achievementTag=b=>achievement(b)?'<span class="achievement-tag achievement-'+esc(b)+'" title="'+esc(b)+'"><span aria-hidden="true">'+achievement(b)+'</span></span>':'';
function letterHtml(text,styles){const a=Array.isArray(styles)?styles:[];return [...String(text||'')].map((ch,i)=>{const s=a[i]||{},c=String(s.color||'').toLowerCase(),fx=safeEffect(s.effect),rainbow=c==='rainbow',hex=/^#[0-9a-f]{6}$/i.test(c)?c:'';return '<span class="name-letter'+(rainbow?' name-rainbow':'')+' effect-'+fx+'"'+(hex?' style="color:'+hex+'"':'')+'>'+esc(ch)+'</span>'}).join('')}
function styledName(p){const c=String(p?.nameColor||'#fff').toLowerCase(),fx=safeEffect(p?.nameEffect),v=Number(p?.vipLevel||0),per=v>0&&Array.isArray(p?.letterStyles)&&p.letterStyles.length>0,rainbow=c==='rainbow'&&!per,hex=/^#[0-9a-f]{6}$/i.test(c)?c:'#fff',body=per?letterHtml(p.visualName||p.name,p.letterStyles):[...String(p.visualName||p.name||'PLAYER')].map(x=>'<span class="name-letter">'+esc(x)+'</span>').join('');return '<span class="rank-player-name'+(rainbow?' name-rainbow':'')+(fx!=='none'?' effect-'+fx:'')+(per?' vip-letter-styled':'')+'"'+(rainbow?'':' style="color:'+hex+'"')+'>'+body+'</span>'}
function tags(p,isWorld){let s='';const w=Number(p.worldRank||p.rank||0),c=Number(p.countryRank||0);if(isWorld){if(w>=1&&w<=3)s+=medal('world',w,'');if(w>3&&c>=1&&c<=3)s+=medal('country',c,String(p.country||'').toUpperCase())}else if(c>=1&&c<=3)s+=medal('country',c,String(p.country||'').toUpperCase());return s+achievementTag(p.featuredBadge)+vip(p.vipLevel)}
function renderPulse(list,target,isWorld){if(!target)return;if(!list?.length){target.innerHTML='<li class="empty-row">'+(window.eixoT?window.eixoT('emptyRanking','NO PLAYERS YET'):'NO PLAYERS YET')+'</li>';return}target.innerHTML=list.slice(0,10).map((p,i)=>'<li><span class="rank-number">'+(i+1)+'</span><span class="rank-name-wrap">'+styledName(p)+tags(p,isWorld)+'</span><span class="rank-score-wrap"><span class="rank-flag" title="'+esc(p.country)+'">'+flag(p.country)+'</span><span class="rank-score">'+Number(p.score||0)+'</span></span></li>').join('');window.eixoApplyNameEffects?.()}
function playerLocal(){try{return window.eixoGetPlayer?.()||JSON.parse(localStorage.getItem('eixo_player')||'null')}catch(_){return window.eixoGetPlayer?.()||null}}
function country(){return String(playerLocal()?.country||'PT').toUpperCase()}
function setMyRank(id,n){const e=document.getElementById(id),v=Number(n);if(!e)return;const ok=Number.isInteger(v)&&v>0;e.textContent=ok?rankLabel()+' '+v:'';e.hidden=!ok}
function ensureRankLabels(){const w=document.querySelector('#worldRanking')?.closest('.board')?.querySelector('.board-title'),c=document.querySelector('#nationalRanking')?.closest('.board')?.querySelector('.board-title');if(w&&!document.getElementById('worldMyRank')){const x=document.createElement('span');x.id='worldMyRank';x.className='board-my-rank';x.hidden=true;w.appendChild(x)}if(c&&!document.getElementById('nationalMyRank')){const x=document.createElement('span');x.id='nationalMyRank';x.className='board-my-rank';x.hidden=true;c.appendChild(x)}}
async function loadPulse(){if(!worldEl||!countryEl||window.eixoJumpActive)return;ensureRankLabels();const code=country(),p=playerLocal();try{const req=[fetch('/api/pulse/orbit/rankings?page=1',{cache:'no-store'}),fetch('/api/pulse/orbit/rankings?country='+encodeURIComponent(code)+'&page=1',{cache:'no-store'})];if(p?.id)req.push(fetch('/api/pulse/orbit/player-rank?id='+encodeURIComponent(p.id),{cache:'no-store',credentials:'same-origin'}));const rs=await Promise.all(req);if(!rs[0].ok||!rs[1].ok)throw Error();const [w,c]=await Promise.all([rs[0].json(),rs[1].json()]);if(window.eixoJumpActive)return;renderPulse(w.players,worldEl,true);renderPulse(c.players,countryEl,false);if(rs[2]&&rs[2].ok){const me=await rs[2].json();setMyRank('worldMyRank',me.worldRank);setMyRank('nationalMyRank',me.countryRank)}else{setMyRank('worldMyRank',w.players.find(x=>x.id===p?.id)?.worldRank);setMyRank('nationalMyRank',c.players.find(x=>x.id===p?.id)?.countryRank)}}catch(_){setMyRank('worldMyRank',null);setMyRank('nationalMyRank',null)}}

let styleCache={at:0,map:new Map()},stylePromise=null;
async function styleRoster(force=false){if(!force&&Date.now()-styleCache.at<15000&&styleCache.map.size)return styleCache.map;if(stylePromise)return stylePromise;stylePromise=(async()=>{const r=await fetch('/api/rankings?page=1',{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw Error('styles');const d=await r.json(),pages=Math.min(30,Math.max(1,Number(d.pages)||1)),rows=[...(d.players||[])];if(pages>1){const more=await Promise.all(Array.from({length:pages-1},(_,i)=>fetch('/api/rankings?page='+(i+2),{credentials:'same-origin',cache:'no-store'}).then(x=>x.ok?x.json():{players:[]})));more.forEach(x=>rows.push(...(x.players||[])))}styleCache={at:Date.now(),map:new Map(rows.map(p=>[String(p.id),p]))};return styleCache.map})().finally(()=>stylePromise=null);return stylePromise}
function runTime(ms){const n=Math.max(0,Math.floor(Number(ms)||0));return String(Math.floor(n/60000)).padStart(2,'0')+':'+String(Math.floor((n%60000)/1000)).padStart(2,'0')+'.'+String(n%1000).padStart(3,'0')}
function mergeRun(rows,map){return (rows||[]).map(p=>{const s=map.get(String(p.playerId||p.id))||{};return {...s,...p,id:p.playerId||p.id,visualName:s.visualName||p.name,worldRank:Number(p.rank||p.worldRank||0),countryRank:Number(p.countryRank||0),letterStyles:Array.isArray(s.letterStyles)?s.letterStyles:[]}})}
function runRows(rows,isWorld){if(!rows.length)return '<li class="empty-row">'+(lang()==='pt'?'Ainda não há tempos registados.':'No times recorded yet.')+'</li>';return rows.slice(0,50).map((p,i)=>'<li><span class="rank-number">'+(isWorld?Number(p.worldRank||i+1):Number(p.countryRank||i+1))+'</span><span class="rank-name-wrap">'+styledName(p)+tags(p,isWorld)+'</span><span class="rank-score-wrap eixo-run-score-wrap"><span class="rank-flag" title="'+esc(p.country)+'">'+flag(p.country)+'</span><span class="rank-score eixo-run-score"><b>L'+String(Number(p.level)||0).padStart(3,'0')+'</b><em>'+runTime(p.timeMs)+'</em></span></span></li>').join('')}
let runBusy=false,lastRun=0;
async function enhanceRun(force=false){const view=document.querySelector('.rx-run-ranking-view');if(!view)return;const b=document.querySelector('[data-rx-board="run"]');if(b&&b.getAttribute('aria-pressed')!=='true'&&!b.classList.contains('active'))return;if(runBusy||(!force&&view.dataset.eixoRunStyled==='1'&&Date.now()-lastRun<3500))return;runBusy=true;try{const [rr,styles]=await Promise.all([fetch('/api/run/rankings?limit=50',{credentials:'same-origin',cache:'no-store'}),styleRoster()]);if(!rr.ok)throw Error();const d=await rr.json(),w=mergeRun(d.players,styles),n=mergeRun(d.countryPlayers,styles),cc=String(d.country||d.me?.country||country()).toUpperCase(),me=d.me||null;view.innerHTML='<section class="boards eixo-run-boards"><article class="board"><div class="board-title"><span>🌐</span><span>TOP MUNDIAL</span><span class="board-my-rank">'+(me?.rank?rankLabel()+' '+me.rank:'')+'</span></div><ol>'+runRows(w,true)+'</ol></article><article class="board"><div class="board-title"><span>'+flag(cc)+'</span><span>TOP '+esc(cc==='PT'?'PORTUGAL':cc)+'</span><span class="board-my-rank">'+(me?.countryRank?rankLabel()+' '+me.countryRank:'')+'</span></div><ol>'+runRows(n,false)+'</ol></article></section>';view.dataset.eixoRunStyled='1';lastRun=Date.now();window.eixoApplyNameEffects?.()}catch(_){}finally{runBusy=false}}
const scheduleRun=(force=false)=>setTimeout(()=>enhanceRun(force),80);

const AVATAR={default:'◆',diamond:'◇',square:'■',circle:'●',star:'★',bolt:'⚡',shield:'⬢',hex:'⬡',crystal:'✦',spark:'✧',comet:'☄',crown:'♛',thunder:'ϟ',skull:'☠',phoenix:'♨',vortex:'◉',titan:'♜',plasma:'✺',infinity:'∞',cosmic:'✹',prism:'◈'};
const safeClass=v=>String(v||'').replace(/[^a-z0-9-]/gi,'').toLowerCase();
function patchAvatar(){const panel=document.querySelector('#rx-passport .rx-passport-seal-panel');if(!panel)return;if(!panel.querySelector('#rxPassportAvatar')){panel.innerHTML='<div class="rx-passport-avatar-stage"><div id="rxPassportAvatar" class="rx-passport-avatar"><span></span></div></div><div class="rx-passport-seal-caption">AVATAR DO JOGADOR</div>';panel.dataset.eixoAvatarPatched='1'}const p=playerLocal(),e=panel.querySelector('#rxPassportAvatar');if(!e)return;const av=String(p?.avatar||'default'),bd=String(p?.avatarBorder||'#46535f').toLowerCase(),cls='rx-passport-avatar avatar-'+safeClass(av)+(bd.startsWith('#')?'':' border-'+safeClass(bd)),glyph=window.eixoAvatarGlyph?.(av)||AVATAR[av]||'◆';if(e.className!==cls)e.className=cls;const span=e.querySelector('span');if(span&&span.textContent!==glyph)span.textContent=glyph;const border=/^#[0-9a-f]{6}$/i.test(bd)?bd:'';if(e.style.borderColor!==border)e.style.borderColor=border}

const style=document.createElement('style');style.textContent=`
.eixo-booting>.eixo-boot-screen{background:radial-gradient(circle at 50% 50%,#202949 0,transparent 32%),#080d15!important}
.eixo-run-boards{width:100%}.eixo-run-boards .board-title{display:flex;align-items:center;gap:9px}.eixo-run-boards .board-title .board-my-rank{margin-left:auto}.eixo-run-score-wrap{min-width:190px;justify-content:flex-end}.eixo-run-score{display:flex!important;align-items:center;gap:12px;white-space:nowrap}.eixo-run-score b{font:800 11px/1 Inter,Arial,sans-serif;color:#b49aff}.eixo-run-score em{font:800 10px/1 ui-monospace,SFMono-Regular,Consolas,monospace;color:#e2e9f4;font-style:normal}
.rx-passport-avatar-stage{position:relative;min-height:355px;display:grid;place-items:center;border:1px solid #62759b67;border-radius:17px;background:radial-gradient(circle at 50% 42%,#343a67 0,#1d2942 42%,#0f1a2c 78%);overflow:hidden}.rx-passport-avatar-stage:before{content:"";position:absolute;width:220px;height:220px;border:1px solid #a9a5e32e;border-radius:50%;box-shadow:0 0 0 42px #a7acf008,0 0 0 82px #a7acf005}.rx-passport-avatar{position:relative;z-index:2;width:142px;height:142px;display:grid;place-items:center;border:4px solid #46535f;border-radius:30px;background:linear-gradient(145deg,#242f43,#0e1725);box-shadow:0 22px 50px #0509148f,inset 0 1px #ffffff30;color:#f4f7ff;font:72px/1 Arial,sans-serif;transition:.2s}.rx-passport-avatar>span{position:relative;z-index:2;filter:drop-shadow(0 5px 8px #0007)}
.rx-passport-avatar.border-glow-blue{border-color:#00d4ff;box-shadow:0 0 16px #00d4ff,0 22px 50px #0509148f}.rx-passport-avatar.border-glow-yellow{border-color:#ffd43b;box-shadow:0 0 16px #ffd43b,0 22px 50px #0509148f}.rx-passport-avatar.border-pulse-green{border-color:#39d98a;animation:rxAvPG 1.1s ease-in-out infinite}.rx-passport-avatar.border-pulse-purple{border-color:#b66cff;animation:rxAvPP 1.1s ease-in-out infinite}.rx-passport-avatar.border-electric-yellow{border-color:#ffd43b;animation:rxAvEl .32s steps(2,end) infinite}.rx-passport-avatar.border-electric-blue{border-color:#00d4ff;animation:rxAvEl .32s steps(2,end) infinite}.rx-passport-avatar.border-flame-orange{border-color:#ff7a2f;animation:rxAvFO .65s ease-in-out infinite alternate}.rx-passport-avatar.border-flame-red{border-color:#ef4444;animation:rxAvFR .65s ease-in-out infinite alternate}.rx-passport-avatar.border-plasma-cyan{border-color:#00e5ff;box-shadow:0 0 10px #00e5ff,0 0 24px #7c4dff;animation:rxAvPl 1.2s linear infinite}.rx-passport-avatar.border-plasma-purple{border-color:#c084fc;box-shadow:0 0 10px #c084fc,0 0 24px #ff4fd8;animation:rxAvPl 1.2s linear infinite}.rx-passport-avatar.border-cosmic{border-color:#7c4dff;box-shadow:0 0 12px #7c4dff,0 0 26px #00e5ff,0 0 38px #ff4fd8;animation:rxAvCo 1.8s ease-in-out infinite}.rx-passport-avatar.border-infinity-rgb,.rx-passport-avatar.border-rainbow{animation:rxAvRgb 1.55s linear infinite}
@keyframes rxAvPG{50%{box-shadow:0 0 24px #39d98a}}@keyframes rxAvPP{50%{box-shadow:0 0 24px #b66cff}}@keyframes rxAvEl{50%{filter:brightness(1.7);transform:translateX(1px)}}@keyframes rxAvFO{to{box-shadow:0 -8px 16px #ff7a2f,0 -17px 28px #ef4444}}@keyframes rxAvFR{to{box-shadow:0 -8px 16px #ef4444,0 -17px 28px #ff7a2f}}@keyframes rxAvPl{50%{filter:hue-rotate(80deg)}}@keyframes rxAvCo{50%{transform:scale(1.04);filter:hue-rotate(80deg)}}@keyframes rxAvRgb{0%{border-color:#ff4d4d;box-shadow:0 0 22px #ff4d4d}17%{border-color:#ffd43b;box-shadow:0 0 22px #ffd43b}34%{border-color:#39d98a;box-shadow:0 0 22px #39d98a}51%{border-color:#00d4ff;box-shadow:0 0 22px #00d4ff}68%{border-color:#6f5cff;box-shadow:0 0 22px #6f5cff}85%{border-color:#ff4fd8;box-shadow:0 0 22px #ff4fd8}100%{border-color:#ff4d4d;box-shadow:0 0 22px #ff4d4d}}@media(max-width:700px){.rx-passport-avatar-stage{min-height:280px}.rx-passport-avatar{width:118px;height:118px;font-size:60px}}
`;document.head.appendChild(style);

const finishBoot=()=>{document.body?.classList.remove('eixo-booting');document.body?.classList.add('eixo-ready')};window.addEventListener('load',()=>setTimeout(finishBoot,120),{once:true});setTimeout(finishBoot,2500);
window.eixoRefreshRankings=loadPulse;window.loadTopRankings=loadPulse;if(worldEl&&countryEl)loadPulse();
window.addEventListener('eixo-player-updated',()=>{styleCache.at=0;loadPulse();patchAvatar();scheduleRun(true)});window.addEventListener('eixo-outfit-updated',()=>{patchAvatar();scheduleRun(true)});window.addEventListener('popstate',()=>{scheduleRun(true);setTimeout(patchAvatar,80)});document.addEventListener('visibilitychange',()=>{if(!document.hidden){loadPulse();scheduleRun(true);patchAvatar()}});document.addEventListener('click',e=>{if(e.target.closest?.('[data-rx-board="run"],[data-rx-route="rankings"]'))scheduleRun(true);if(e.target.closest?.('[data-rx-route="passport"]'))setTimeout(patchAvatar,100)},true);
setInterval(()=>{loadPulse();if(location.pathname.replace(/\/$/,'')==='/rankings')scheduleRun(true)},5000);
new MutationObserver(()=>{if(document.querySelector('.rx-run-ranking-view'))scheduleRun(false);const panel=document.querySelector('#rx-passport .rx-passport-seal-panel');if(panel&&!panel.querySelector('#rxPassportAvatar'))patchAvatar()}).observe(document.documentElement,{childList:true,subtree:true});
})();
