/* EIXO ranking renderer: live Top 5, tags, flags and visual-name styling. */
(function(){
 const worldEl=document.getElementById('worldRanking'),countryEl=document.getElementById('nationalRanking');if(!worldEl||!countryEl)return;
 const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
 const flag=code=>[...String(code||'')].map(c=>String.fromCodePoint(127397+c.charCodeAt())).join('');
 const tag=(type,n,country)=>`<span class="rank-tag ${type}-${n}">${n}# ${type==='country'?esc(country):'GLOBAL'}</span>`;const vipTag=n=>n>0?`<span class="vip-rank-tag vip-rank-${Math.min(n,6)}">${n>=6?'VIP ∞':`VIP #${n}`}</span>`:'';const letters=(text,styles)=>{const arr=Array.isArray(styles)?styles:[];return [...String(text||'')].map((ch,i)=>{const s=arr[i]||{};const color=String(s.color||'').toLowerCase();const effect=String(s.effect||'none');const safeColor=/^#[0-9a-f]{6}$/i.test(color)?color:'';const safeEffect=/^[a-z]+$/.test(effect)?effect:'none';return `<span class="name-letter effect-${safeEffect}" style="${safeColor?'color:'+safeColor+';':''}">${esc(ch)}</span>`}).join('')};
 function render(list,target,isWorld){if(!list?.length){target.innerHTML='<li class="empty-row">AINDA SEM JOGADORES</li>';return}target.innerHTML=list.slice(0,5).map((p,i)=>{let tags='';if(isWorld){if(Number(p.worldRank)<=3)tags+=tag('world',Number(p.worldRank));if(Number(p.worldRank)>3&&Number(p.countryRank)<=3)tags+=tag('country',Number(p.countryRank),String(p.country||'').toUpperCase());}else if(Number(p.countryRank)<=3)tags+=tag('country',Number(p.countryRank),String(p.country||'').toUpperCase());const color=String(p.nameColor||'#fff').toLowerCase(),rainbow=color==='rainbow',colorStyle=rainbow?'':' style="color:'+esc(color)+';"',effect=p.nameEffect&&p.nameEffect!=='none'?` effect-${esc(p.nameEffect)}`:'',vip=Number(p.vipLevel||0);const hasLetters=vip>0&&Array.isArray(p.letterStyles)&&p.letterStyles.length;return `<li><span class="rank-number">${i+1}</span><span class="rank-name-wrap"><span class="rank-player-name${rainbow?' name-rainbow':''}${effect}${hasLetters?' vip-letter-styled':''}"${colorStyle}>${hasLetters?letters(p.visualName||p.name,p.letterStyles):[...String(p.visualName||p.name)].map(ch=>`<span class="name-letter">${esc(ch)}</span>`).join('')}</span>${tags}${vipTag(vip)}</span><span class="rank-score-wrap"><span class="rank-flag" title="${esc(p.country)}">${flag(p.country)}</span><span class="rank-score">${Number(p.score||0)}</span></span></li>`}).join('')}
 function registeredCountry(){try{const p=JSON.parse(localStorage.getItem('eixo_player')||'null');if(p?.country)return String(p.country).toUpperCase()}catch(_){}return 'PT'}
 async function load(){const code=registeredCountry();try{const [wr,cr]=await Promise.all([fetch('/api/rankings?page=1',{cache:'no-store'}),fetch('/api/rankings?country='+encodeURIComponent(code)+'&page=1',{cache:'no-store'})]);if(!wr.ok||!cr.ok)throw Error();const [w,c]=await Promise.all([wr.json(),cr.json()]);render(w.players,worldEl,true);render(c.players,countryEl,false)}catch(_){} }
 window.eixoRefreshRankings=load;window.loadTopRankings=load;load();setInterval(load,2000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});
})();
