(() => {
  const playerButton=document.getElementById('playerButton'),playerMenu=document.getElementById('playerMenu'),playerName=document.getElementById('playerName'),countryButton=document.getElementById('countryButton'),countryMenu=document.getElementById('countryMenu');
  if(!playerButton||!playerMenu||!playerName)return;
  const labels={pt:{contact:'CONTACTO',bugs:'REPORTAR BUGS',customize:'PERSONALIZAR NOME',vip:'VIP'},en:{contact:'CONTACT',bugs:'REPORT BUGS',customize:'CUSTOMIZE NAME',vip:'VIP'},es:{contact:'CONTACTAR',bugs:'REPORTAR BUGS',customize:'PERSONALIZAR NOMBRE',vip:'VIP'},fr:{contact:'CONTACTER',bugs:'SIGNALER UN BUG',customize:'PERSONNALISER LE NOM',vip:'VIP'},de:{contact:'KONTAKT',bugs:'BUG MELDEN',customize:'NAMEN ANPASSEN',vip:'VIP'},it:{contact:'CONTATTI',bugs:'SEGNALA BUG',customize:'PERSONALIZZA NOME',vip:'VIP'},ja:{contact:'お問い合わせ',bugs:'バグを報告',customize:'名前を変更',vip:'VIP'},ko:{contact:'문의하기',bugs:'버그 신고',customize:'이름 변경',vip:'VIP'},zh:{contact:'联系',bugs:'报告错误',customize:'自定义名称',vip:'VIP'},ru:{contact:'КОНТАКТ',bugs:'СООБЩИТЬ ОБ ОШИБКЕ',customize:'ИЗМЕНИТЬ ИМЯ',vip:'VIP'},pl:{contact:'KONTAKT',bugs:'ZGŁOŚ BŁĄD',customize:'ZMIENIĆ NAZWĘ',vip:'VIP'},nl:{contact:'CONTACT',bugs:'BUG MELDEN',customize:'NAAM AANPASSEN',vip:'VIP'},tr:{contact:'İLETİŞİM',bugs:'HATA BİLDİR',customize:'ADI ÖZELLEŞTİR',vip:'VIP'},ar:{contact:'تواصل',bugs:'الإبلاغ عن خطأ',customize:'تخصيص الاسم',vip:'VIP'}};
  const lang=()=>document.documentElement.lang||'en';
  function render(){let p=null;try{p=JSON.parse(localStorage.getItem('eixo_player')||'null')}catch(_){}playerName.textContent=p?.name||'JOGADOR';const t=labels[lang()]||labels.en;playerMenu.innerHTML=`<button type="button" class="player-option vip-menu-option" data-action="vip">◆ ${t.vip}</button><button type="button" class="player-option" data-action="customize">${t.customize}</button><button type="button" class="player-option" data-action="bugs">${t.bugs}</button><button type="button" class="player-option" data-action="suggestions">SUGESTÕES</button><button type="button" class="player-option" data-action="contact">${t.contact}</button>`;}
  playerButton.addEventListener('click',e=>{e.stopPropagation();const open=playerMenu.classList.toggle('open');playerButton.setAttribute('aria-expanded',String(open));});
  function openMenuAction(action){if(action==='contact'){document.getElementById('contactModal')?.classList.remove('hidden');return}if(action==='bugs'){document.getElementById('bugModal')?.classList.remove('hidden');return}if(action==='suggestions'){const m=document.getElementById('contactModal');if(m){m.classList.remove('hidden');const s=m.querySelector('[name="subject"]');if(s)s.value='SUGESTÃO';const h=m.querySelector('h2');if(h)h.textContent='SUGESTÕES';}return}window.dispatchEvent(new CustomEvent('eixo-player-menu',{detail:{action}}));}
  playerMenu.addEventListener('click',e=>{const b=e.target.closest('.player-option');if(!b)return;playerMenu.classList.remove('open');playerButton.setAttribute('aria-expanded','false');openMenuAction(b.dataset.action);});
  if(countryButton&&countryMenu){countryButton.addEventListener('click',e=>{e.stopPropagation();const open=countryMenu.classList.toggle('open');countryButton.setAttribute('aria-expanded',String(open));});countryMenu.addEventListener('click',e=>{const b=e.target.closest('.country-option');if(!b)return;const c=b.dataset.country;if(typeof window.changeCountry==='function')window.changeCountry(c);countryMenu.classList.remove('open');countryButton.setAttribute('aria-expanded','false');render();});}
  const rankingTabs=document.querySelector('.ranking-tabs'),worldTab=document.getElementById('modalWorldTab'),countryTab=document.getElementById('modalCountryTab');if(rankingTabs&&worldTab&&countryTab)rankingTabs.append(worldTab,countryTab);
  document.addEventListener('click',e=>{if(!e.target.closest('.player-area')){playerMenu.classList.remove('open');playerButton.setAttribute('aria-expanded','false')}if(!e.target.closest('.profile-area')){countryMenu?.classList.remove('open');countryButton?.setAttribute('aria-expanded','false')}});
  render();window.addEventListener('storage',render);window.addEventListener('eixo-player-updated',render);
})();
