(() => {
  const playerButton=document.getElementById('playerButton'),playerMenu=document.getElementById('playerMenu'),playerName=document.getElementById('playerName'),vipTopButton=document.getElementById('vipTopButton'),vipTopMenu=document.getElementById('vipTopMenu'),countryButton=document.getElementById('countryButton'),countryMenu=document.getElementById('countryMenu');
  if(!playerButton||!playerMenu||!playerName)return;
  const labels={pt:{contact:'CONTACTO',bugs:'REPORTAR BUGS',customize:'PERSONALIZAR NOME',vip:'VIP'},en:{contact:'CONTACT',bugs:'REPORT BUGS',customize:'CUSTOMIZE NAME',vip:'VIP'},es:{contact:'CONTACTAR',bugs:'REPORTAR BUGS',customize:'PERSONALIZAR NOMBRE',vip:'VIP'},fr:{contact:'CONTACTER',bugs:'SIGNALER UN BUG',customize:'PERSONNALISER LE NOM',vip:'VIP'},de:{contact:'KONTAKT',bugs:'BUG MELDEN',customize:'NAMEN ANPASSEN',vip:'VIP'},it:{contact:'CONTATTI',bugs:'SEGNALA BUG',customize:'PERSONALIZZA NOME',vip:'VIP'},ja:{contact:'お問い合わせ',bugs:'バグを報告',customize:'名前を変更',vip:'VIP'},ko:{contact:'문의하기',bugs:'버그 신고',customize:'이름 변경',vip:'VIP'},zh:{contact:'联系',bugs:'报告错误',customize:'自定义名称',vip:'VIP'},ru:{contact:'КОНТАКТ',bugs:'СООБЩИТЬ ОБ ОШИБКЕ',customize:'ИЗМЕНИТЬ ИМЯ',vip:'VIP'},pl:{contact:'KONTAKT',bugs:'ZGŁOŚ BŁĄD',customize:'ZMIENIĆ NAZWĘ',vip:'VIP'},nl:{contact:'CONTACT',bugs:'BUG MELDEN',customize:'NAAM AANPASSEN',vip:'VIP'},tr:{contact:'İLETİŞİM',bugs:'HATA BİLDİR',customize:'ADI ÖZELLEŞTİR',vip:'VIP'},ar:{contact:'تواصل',bugs:'الإبلاغ عن خطأ',customize:'تخصيص الاسم',vip:'VIP'}};
  const lang=()=>document.documentElement.lang||'en';
  function render(){let p=null;try{p=JSON.parse(localStorage.getItem('eixo_player')||'null')}catch(_){}playerName.textContent=p?.name||'JOGADOR';const t=labels[lang()]||labels.en;playerMenu.innerHTML=`<button type="button" class="player-option" data-action="customize">${t.customize}</button><button type="button" class="player-option vip-menu-toggle" data-action="vip" aria-expanded="false">${t.vip}</button><div class="vip-submenu" role="menu"><button type="button" class="player-option vip-sub-option" data-action="vip-buy">COMPRAR VIP</button><button type="button" class="player-option vip-sub-option" data-action="vip-customize">PERSONALIZAR NOME VIP</button></div><button type="button" class="player-option" data-action="bugs">${t.bugs}</button><button type="button" class="player-option" data-action="suggestions">SUGESTÕES</button><button type="button" class="player-option" data-action="contact">${t.contact}</button>`;}
  vipTopButton?.addEventListener('click',e=>{e.stopPropagation();const open=vipTopMenu?.classList.toggle('open');vipTopButton.setAttribute('aria-expanded',String(!!open));});
  vipTopMenu?.addEventListener('click',e=>{const b=e.target.closest('[data-vip-action]');if(!b)return;vipTopMenu.classList.remove('open');vipTopButton?.setAttribute('aria-expanded','false');if(b.dataset.vipAction==='buy'){window.eixoOpenVip?.();}else if(b.dataset.vipAction==='customize'){const p=(()=>{try{return JSON.parse(localStorage.getItem('eixo_player')||'null')}catch(_){return null}})();if(Number(p?.vipLevel||0)>0)window.eixoOpenVipCustomize?.();else window.eixoOpenVip?.();}});

  playerButton.addEventListener('click',e=>{e.stopPropagation();const open=playerMenu.classList.toggle('open');playerButton.setAttribute('aria-expanded',String(open));});
  function openMenuAction(action){
  if(action==='customize'){if(window.eixoOpenCustomize){window.eixoOpenCustomize();return}window.dispatchEvent(new CustomEvent('eixo-player-menu',{detail:{action:'customize'}}));return}
  if(action==='vip'){const open=playerMenu.classList.toggle('vip-open');const b=playerMenu.querySelector('.vip-menu-toggle');b?.setAttribute('aria-expanded',String(open));return}
  if(action==='vip-buy'){if(window.eixoOpenVip)window.eixoOpenVip();return}
  if(action==='vip-customize'){
    let p=null;try{p=JSON.parse(localStorage.getItem('eixo_player')||'null')}catch(_){}
    if(Number(p?.vipLevel||0)>0&&window.eixoOpenVipCustomize){window.eixoOpenVipCustomize();}else if(window.eixoOpenVip){window.eixoOpenVip();}
    return
  }
  if(action==='contact'){document.getElementById('contactModal')?.classList.remove('hidden');return}
  if(action==='bugs'){document.getElementById('bugModal')?.classList.remove('hidden');return}
  if(action==='suggestions'){document.getElementById('suggestionModal')?.classList.remove('hidden');return}
  window.dispatchEvent(new CustomEvent('eixo-player-menu',{detail:{action}}));
}
  playerMenu.addEventListener('click',e=>{const b=e.target.closest('.player-option');if(!b)return;const action=b.dataset.action;if(action==='vip'){openMenuAction(action);return;}playerMenu.classList.remove('open','vip-open');playerButton.setAttribute('aria-expanded','false');openMenuAction(action);});
  if(countryButton&&countryMenu){countryButton.addEventListener('click',e=>{e.stopPropagation();const open=countryMenu.classList.toggle('open');countryButton.setAttribute('aria-expanded',String(open));});countryMenu.addEventListener('click',e=>{const b=e.target.closest('.country-option');if(!b)return;const c=b.dataset.country;if(typeof window.changeCountry==='function')window.changeCountry(c);countryMenu.classList.remove('open');countryButton.setAttribute('aria-expanded','false');render();});}
  const rankingTabs=document.querySelector('.ranking-tabs'),worldTab=document.getElementById('modalWorldTab'),countryTab=document.getElementById('modalCountryTab');if(rankingTabs&&worldTab&&countryTab)rankingTabs.append(worldTab,countryTab);
  document.addEventListener('click',e=>{if(!e.target.closest('.player-area')){playerMenu.classList.remove('open','vip-open');playerMenu.querySelector('.vip-menu-toggle')?.setAttribute('aria-expanded','false');playerButton.setAttribute('aria-expanded','false')}if(!e.target.closest('.vip-top-area')){vipTopMenu?.classList.remove('open');vipTopButton?.setAttribute('aria-expanded','false')}if(!e.target.closest('.profile-area')){countryMenu?.classList.remove('open');countryButton?.setAttribute('aria-expanded','false')}});
  document.querySelectorAll('.modal-close[data-close-modal]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.closeModal)?.classList.add('hidden')));
  document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));
  render();window.addEventListener('storage',render);window.addEventListener('eixo-player-updated',render);
})();
