/* EIXO VIP test layer. The purchase endpoint is intentionally a test-only route for now. */
(function(){
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;'}[c]));
 const colors=['#f5f7ff','#00e5ff','#7c4dff','#ff4fd8','#ff6b6b','#7cff6b','#00bfa6','#ff9f1c','#d9ff00','#c084fc'];
 const effects=[['none','Nenhum'],['sparkle','Faísca'],['shimmer','Brilho'],['glitch','Glitch'],['tilt','Inclina'],['pop','Pop'],['scanline','Scan']];
 const vipTagColors=['#f5f7ff','#00e5ff','#ffe66d','#7cff6b','#ff6b8a','#ffd166'];
 const get=()=>{try{return JSON.parse(localStorage.getItem('eixo_player')||'null')}catch(_){return null}};
 const auth=()=>{const p=get();return p?.id&&p?.token?{id:p.id,token:p.token}:null};
 const open=m=>m?.classList.remove('hidden'),close=m=>m?.classList.add('hidden');
 function addModal(){if($('vipModal'))return;const m=document.createElement('div');m.id='vipModal';m.className='modal-backdrop hidden';m.innerHTML=\`<div class="modal-card form-modal vip-modal" role="dialog" aria-modal="true"><button class="modal-close" id="vipClose" type="button">✕</button><div class="vip-mark">◆ VIP</div><h2 id="vipTitle">EIXO VIP</h2><p id="vipStatus">Ainda não tens VIP.</p><div class="vip-levels" id="vipLevels"></div><div class="vip-benefits"><strong>BENEFÍCIOS VIP</strong><ul><li>Nome visual com espaços e caracteres especiais</li><li>Cores e animações independentes por letra</li><li>10 cores exclusivas VIP</li><li>Salas privadas maiores conforme o nível</li><li>A TAG VIP fica permanentemente na conta</li></ul></div><button class="modal-button primary" id="vipBuy" type="button">COMPRAR VIP (TESTE) ▶</button><div class="form-error" id="vipError"></div></div>\`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)close(m)});$('vipClose').addEventListener('click',()=>close(m));$('vipBuy').addEventListener('click',buy);}
 function renderLevels(level){const el=$('vipLevels');if(!el)return;el.innerHTML=Array.from({length:6},(_,i)=>{const n=i+1,active=n<=level;return \`<span class="vip-level \${active?'active':''}" style="--vip:#${vipTagColors[i].slice(1)}">VIP #${n}</span>\`}).join('');}
 function openVip(){addModal();const p=get(),level=Number(p?.vipLevel||0),status=$('vipStatus'),buy=$('vipBuy');renderLevels(level);status.textContent=level?\`Tens VIP #${level}. O VIP é permanente.\`:'Ainda não tens VIP.';buy.textContent=level>=6?'VIP MÁXIMO ATINGIDO':\`COMPRAR VIP \${level+1} (TESTE) ▶\`;buy.disabled=level>=6;$('vipError').textContent='';open($('vipModal'));}
 async function buy(){const a=auth();if(!a)return;const b=$('vipBuy'),err=$('vipError');b.disabled=true;err.textContent='';try{const r=await fetch('/api/vip/test-purchase',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(a)}),d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível ativar o VIP.');localStorage.setItem('eixo_player',JSON.stringify({...get(),...d.player,token:a.token}));window.dispatchEvent(new Event('eixo-player-updated'));renderLevels(d.level);refreshRoomSizes();openVip();}catch(e){err.textContent=e.message;b.disabled=false;}}
 function vipEffectOptions(selected){return effects.map(([v,l])=>\`<option value="\${v}" \${v===selected?'selected':''}>\${l}</option>\`).join('');}
 function vipColorOptions(selected){return colors.map(c=>\`<option value="\${c}" \${c===selected?'selected':''}>\${c}</option>\`).join('');}
 function letterHtml(text,styles){return [...String(text||'')].map((ch,i)=>{const s=styles[i]||{},color=s.color||'#f5f7ff',effect=s.effect||'none';return \`<span class="name-letter effect-\${esc(effect)}" style="color:\${esc(color)}">\${esc(ch)}</span>\`}).join('');}
 function addVipCustomize(){if($('vipCustomizeModal'))return;const m=document.createElement('div');m.id='vipCustomizeModal';m.className='modal-backdrop hidden';m.innerHTML=\`<div class="modal-card form-modal vip-customize-modal" role="dialog" aria-modal="true"><button class="modal-close" id="vipCustomizeClose" type="button">✕</button><div class="vip-mark">◆ VIP</div><h2>PERSONALIZAR NOME VIP</h2><p>O teu nome visual pode usar espaços, símbolos e caracteres especiais. Cada letra pode ter a sua própria cor e animação.</p><label class="field-label">NOME VISUAL VIP<input id="vipVisualName" class="pixel-input" maxlength="32" autocomplete="off"></label><div class="vip-preview" id="vipPreview">JOGADOR</div><div class="vip-letter-controls" id="vipLetterControls"></div><div class="form-error" id="vipCustomizeError"></div><button class="modal-button primary" id="vipCustomizeSave" type="button">GUARDAR VIP ▶</button></div>\`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)close(m)});$('vipCustomizeClose').addEventListener('click',()=>close(m));$('vipVisualName').addEventListener('input',renderLetterControls);$('vipCustomizeSave').addEventListener('click',saveVipCustomize);}
 function renderLetterControls(){const input=$('vipVisualName'),wrap=$('vipLetterControls'),preview=$('vipPreview');if(!input||!wrap)return;const p=get()||{},old=Array.isArray(p.letterStyles)?p.letterStyles:[];const text=input.value||'JOGADOR';const styles=[...text].map((_,i)=>old[i]||{color:colors[i%colors.length],effect:effects[(i%6)+1][0]});wrap.innerHTML=[...text].map((ch,i)=>\`<div class="vip-letter-row"><span class="vip-letter-char">\${esc(ch===' '?'␠':ch)}</span><select class="pixel-input vip-letter-color" data-i="\${i}">\${vipColorOptions(styles[i].color)}</select><select class="pixel-input vip-letter-effect" data-i="\${i}">\${vipEffectOptions(styles[i].effect)}</select></div>\`).join('');wrap.querySelectorAll('select').forEach(s=>s.addEventListener('change',renderVipPreview));renderVipPreview();}
 function renderVipPreview(){const input=$('vipVisualName'),wrap=$('vipLetterControls'),preview=$('vipPreview');if(!preview)return;const styles=[...String(input?.value||'')].map((_,i)=>({color:wrap?.querySelector(\`.vip-letter-color[data-i="\${i}"]\`)?.value||colors[i%colors.length],effect:wrap?.querySelector(\`.vip-letter-effect[data-i="\${i}"]\`)?.value||'none'}));preview.innerHTML=letterHtml(input?.value||'JOGADOR',styles);}
 function openVipCustomize(){const p=get();if(!p||!Number(p.vipLevel))return;addVipCustomize();$('vipVisualName').value=p.visualName||p.name||'JOGADOR';renderLetterControls();$('vipCustomizeError').textContent='';open($('vipCustomizeModal'));}
 async function saveVipCustomize(){const a=auth();if(!a)return;const input=$('vipVisualName'),wrap=$('vipLetterControls'),err=$('vipCustomizeError'),text=input.value;const styles=[...text].map((_,i)=>({color:wrap.querySelector(\`.vip-letter-color[data-i="\${i}"]\`)?.value||colors[i%colors.length],effect:wrap.querySelector(\`.vip-letter-effect[data-i="\${i}"]\`)?.value||'none'}));err.textContent='';try{const r=await fetch('/api/profile/customize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:a.id,token:a.token,visualName:text,color:styles[0]?.color||colors[0],effect:styles[0]?.effect||'none',letterStyles:styles})}),d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível guardar.');localStorage.setItem('eixo_player',JSON.stringify({...get(),...d.player,token:a.token}));window.dispatchEvent(new Event('eixo-player-updated'));close($('vipCustomizeModal'));if(window.eixoRefreshRankings)window.eixoRefreshRankings();}catch(e){err.textContent=e.message;}}
 function refreshRoomSizes(){const s=$('roomSizeInput');if(!s)return;const p=get(),level=Number(p?.vipLevel||0),max=level>=4?50:level>=1?20:8,current=Number(s.value||8);s.innerHTML='';for(let i=1;i<=max;i++){const o=document.createElement('option');o.value=String(i);o.textContent=String(i);s.appendChild(o)}s.value=String(Math.min(current,max));}
 function renderVipTags(){document.querySelectorAll('.rank-vip-tag').forEach(e=>e.remove());}
 function css(){if($('vipStyle'))return;const s=document.createElement('style');s.id='vipStyle';s.textContent=\`.vip-mark{font:7px 'Press Start 2P',monospace;color:#00e5ff;margin-bottom:10px}.vip-menu-option{color:#00e5ff!important}.vip-levels{display:grid;grid-template-columns:repeat(6,1fr);gap:6px;margin:15px 0}.vip-level{padding:8px 3px;border:1px solid #34404a;color:#56626d;font:5px 'Press Start 2P',monospace;text-align:center}.vip-level.active{border-color:var(--vip);color:var(--vip);box-shadow:2px 2px 0 #05070a}.vip-benefits{border:1px solid #34404a;background:#080d12;padding:12px;margin:14px 0;color:#9ba5ae;font:6px/1.7 'Press Start 2P',monospace}.vip-benefits strong{color:#f5f7ff;font-size:7px}.vip-benefits ul{margin:8px 0 0;padding-left:18px}.vip-benefits li{margin:5px 0}.vip-preview{margin:15px 0;padding:15px;border:2px solid #34404a;background:#080d12;text-align:center;font:13px/1.5 'Press Start 2P',monospace;min-height:48px}.vip-letter-controls{display:flex;flex-direction:column;gap:6px;max-height:310px;overflow:auto;margin:10px 0}.vip-letter-row{display:grid;grid-template-columns:42px 1fr 1fr;gap:6px;align-items:center}.vip-letter-char{height:34px;display:flex;align-items:center;justify-content:center;border:1px solid #34404a;background:#0b1117;color:#f5f7ff;font:9px 'Press Start 2P',monospace;overflow:hidden}.vip-letter-row .pixel-input{margin:0!important;font-size:5px!important;padding:7px!important}.vip-customize-modal{width:min(680px,100%)}@media(max-width:600px){.vip-levels{grid-template-columns:repeat(3,1fr)}.vip-letter-row{grid-template-columns:32px 1fr 1fr}.vip-letter-row .pixel-input{font-size:4px!important}.vip-preview{font-size:10px}}\`;document.head.appendChild(s)}
 window.eixoOpenVipCustomize=openVipCustomize;
 function bind(){addModal();addVipCustomize();css();refreshRoomSizes();}
 window.addEventListener('eixo-player-menu',e=>{if(e.detail.action==='vip')openVip();else if(e.detail.action==='customize'){const p=get();if(p?.vipLevel){setTimeout(()=>{close($('customizeModal'));openVipCustomize()},0)}}});
 window.addEventListener('eixo-player-updated',refreshRoomSizes);
 bind();setInterval(bind,1000);
})();