'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const P=require('../run/shared/physics');
const flat=(extra={})=>({id:'test',version:1,engineVersion:P.VERSION,spawn:{x:1,y:.01},start:{x:2},finish:{x:30,yMin:-5,yMax:10},killY:-8,gameplay:{solids:[{id:'floor',x:0,y:-1,w:40,h:1}],oneWayPlatforms:[],movingPlatforms:[],hazards:[],shards:[],secrets:[],checkpoints:[],splits:[]},...extra});
function settle(level,s){for(let i=0;i<10;i++)P.step(level,s,{})}
test('RUN accelerates smoothly, caps speed and brakes',()=>{const l=flat(),s=P.create(l);settle(l,s);for(let i=0;i<240;i++)P.step(l,s,{right:true});assert.ok(s.vx>8&&s.vx<=P.C.maxRun);for(let i=0;i<10;i++)P.step(l,s,{});assert.ok(s.vx<8&&s.vx>0);});
test('RUN skid engages on fast reverse without instant direction flip',()=>{const l=flat(),s=P.create(l);settle(l,s);for(let i=0;i<120;i++)P.step(l,s,{right:true});const before=s.vx;P.step(l,s,{left:true});assert.equal(s.skid,true);assert.ok(s.vx<before&&s.vx>0);});
test('variable jump cut makes a shorter jump',()=>{const l=flat();const full=P.create(l),cut=P.create(l);settle(l,full);settle(l,cut);P.step(l,full,{jump:true});P.step(l,cut,{jump:true});for(let i=0;i<18;i++){P.step(l,full,{jump:true});P.step(l,cut,{jump:i<1});}assert.ok(full.y>cut.y+.5);});
test('coyote time permits a late jump after leaving a ledge',()=>{const l=flat();l.gameplay.solids=[{id:'ledge',x:0,y:-1,w:3,h:1}];const s=P.create(l);settle(l,s);s.x=2.8;s.vx=5;let leftAt=-1;for(let i=0;i<40;i++){P.step(l,s,{right:true});if(!s.onGround){leftAt=i;break;}}assert.ok(leftAt>=0);for(let i=0;i<5;i++)P.step(l,s,{right:true});P.step(l,s,{right:true,jump:true});assert.ok(s.vy>8);});
test('jump buffer fires on landing',()=>{const l=flat(),s=P.create(l);s.x=5;s.y=1.4;s.vy=-6;let pressed=false,jumped=false;for(let i=0;i<60;i++){if(!pressed&&s.y<.55){P.step(l,s,{jump:true});pressed=true;}else P.step(l,s,{jump:false});if(pressed&&s.vy>8){jumped=true;break;}}assert.equal(jumped,true);});
test('one-way platforms catch falls but not ascents',()=>{const l=flat();l.gameplay.oneWayPlatforms=[{id:'ow',x:4,y:2,w:4,h:.2}];const s=P.create(l);s.x=5;s.y=0;s.vy=13;let max=0;for(let i=0;i<80;i++){P.step(l,s,{});max=Math.max(max,s.y);if(s.groundId==='ow'&&s.onGround)break;}assert.ok(max>2.25,'player must pass upward through one-way');for(let i=0;i<100&&!s.onGround;i++)P.step(l,s,{});assert.equal(s.groundId,'ow');});
test('moving platform pose is deterministic and bounded',()=>{const p={id:'m',x:5,y:2,w:3,h:.2,axis:'x',amp:2,speed:.5,phase:.2};assert.deepEqual(P.platformPose(p,123),P.platformPose(p,123));for(let i=0;i<1000;i++){const x=P.platformPose(p,i).x;assert.ok(x>=3&&x<=7);}});
test('hazards kill and respawn quickly at start/checkpoint',()=>{const l=flat();l.gameplay.hazards=[{id:'spike',x:2,y:0,w:2,h:1}];const s=P.create(l);settle(l,s);s.x=2.3;P.step(l,s,{});assert.equal(s.dead,true);for(let i=0;i<P.TICKS.respawn;i++)P.step(l,s,{});assert.equal(s.dead,false);assert.equal(s.deaths,1);});
test('shards, secrets and finish are deterministic gameplay state',()=>{const l=flat();l.finish.x=6;l.gameplay.shards=[{id:'a',x:3,y:.7}];l.gameplay.secrets=[{id:'s',x:4,y:0,w:1,h:2}];const s=P.create(l);settle(l,s);for(let i=0;i<240&&!s.finished;i++)P.step(l,s,{right:true});assert.equal(s.finished,true);assert.equal(s.shards.has('a'),true);assert.equal(s.secrets.has('s'),true);assert.ok(P.elapsedMs(s)>0);assert.equal(P.completion(l,s).complete100,true);});
test('same level and inputs produce identical state',()=>{const l=flat(),a=P.create(l),b=P.create(l);for(let i=0;i<600;i++){const input={right:i<500,jump:i%91<8};P.step(l,a,input);P.step(l,b,input);}assert.deepEqual(P.publicState(l,a),P.publicState(l,b));});
