'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
test('RUN is isolated from JUMP and uses a shared deterministic physics core',()=>{const server=read('run-server.js'),physics=read('run/shared/physics.js'),client=read('run/run-client.mjs');assert.match(server,/require\('\.\/run\/shared\/physics'\)/);assert.match(physics,/const DT=1\/120/);assert.match(client,/window\.EixoRunPhysics/);for(const banned of ['jump-motion','jump-rig','jump-physics','jump-exact-renderer','jump-3d-renderer']){assert.doesNotMatch(server,new RegExp(banned));assert.doesNotMatch(client,new RegExp(banned));}});
test('ASTRAL 01 is hand-authored with the approved 42 shards, secret and alternate routes',()=>{const level=JSON.parse(read('run/levels/astral/astral-01.json'));assert.equal(level.id,'astral-01');assert.equal(level.version,1);assert.equal(level.gameplay.shards.length,42);assert.ok(level.gameplay.secrets.length>=1);assert.ok(level.gameplay.movingPlatforms.length>=1);assert.ok(level.gameplay.oneWayPlatforms.some(x=>x.route==='upper-speed'));assert.ok(level.gameplay.oneWayPlatforms.some(x=>x.route==='lower-secret'));assert.ok(level.visuals.far.length&&level.visuals.architecture.length);});
test('RUN has PB and World Echo only, with no multiplayer runtime',()=>{const client=read('run/run-client.mjs'),server=read('run-server.js');assert.match(client,/PB ECHO/);assert.match(client,/WORLD ECHO/);assert.doesNotMatch(client,/LIVE ECHO|FRIEND ECHO|WebSocket|Duo|Trio/i);assert.doesNotMatch(server,/WebSocket|peer sync|lobby|multiplayer/i);});
test('server integration exposes validated RUN routes and keeps run-server private',()=>{const source=read('server.js');assert.match(source,/const runService=require\('\.\/run-server'\)/);assert.match(source,/\/api\/run\/start/);assert.match(source,/\/api\/run\/finish/);assert.match(source,/awardRunEvents/);assert.match(source,/run-server\.js/);assert.match(source,/\/run\/levels\//);});
test('site loads RUN styles, physics and client and exposes /run route',()=>{const html=read('index.html'),redesign=read('redesign.js');assert.match(html,/run\/run\.css/);assert.match(html,/run\/shared\/physics\.js/);assert.match(html,/run\/run-client\.mjs/);assert.match(redesign,/run:'\/run'/);assert.match(redesign,/data-rx-route="run"/);assert.match(redesign,/EixoRun/);});
test('runner atlas is a real multi-frame sprite asset with metadata',()=>{const svg=read('assets/run/character/runner-atlas.svg'),meta=JSON.parse(read('assets/run/character/runner-atlas.json'));assert.match(svg,/width="832"/);assert.ok(meta.animations.run.frames.length>=4);for(const key of ['idle','run','skid','jump-rise','apex','fall','death','victory'])assert.ok(meta.animations[key],key);});
